package net.ibizsys.model;

/**
 * 系统模型集合
 */
public class PSModels {


	public final static String PSDATAENTITY = "PSDATAENTITY"; // 实体
	public final static String PSSYSTEM = "PSSYSTEM"; // 系统
	public final static String PSDEFIELD = "PSDEFIELD"; // 实体属性
	public final static String PSAPPVIEW = "PSAPPVIEW"; // 应用视图
	public final static String PSCODELIST = "PSCODELIST"; // 代码表
	public final static String PSDEACMODE = "PSDEACMODE"; // 实体自填模式
	public final static String PSWORKFLOW = "PSWORKFLOW"; // 工作流
	public final static String PSWFVERSION = "PSWFVERSION"; // 工作流版本
	public final static String PSWFROLE = "PSWFROLE"; // 工作流角色
	public final static String PSDELOGIC = "PSDELOGIC"; // 实体逻辑
	public final static String PSDEDATAQUERY = "PSDEDATAQUERY"; // 实体查询
	public final static String PSDEDATASET = "PSDEDATASET"; // 实体数据集
	public final static String PSSYSAPP = "PSSYSAPP"; // 系统应用
	public final static String PSDEPRINT = "PSDEPRINT"; // 实体打印
	public final static String PSDEREPORT = "PSDEREPORT"; // 实体报表
	public final static String PSPFPKGCAT = "PSPFPKGCAT"; // 应用框架包分类
	public final static String PSCPVISSUE = "PSCPVISSUE"; // 平台核心产品版本修复
	public final static String PSAPPVIEWTEMPL = "PSAPPVIEWTEMPL"; // 应用视图模版
	public final static String PSDCSFPKGVER = "PSDCSFPKGVER"; // 云应用中心服务框架组件版本
	public final static String PSSYSUIACTION = "PSSYSUIACTION"; // 平台预置界面行为
	public final static String PSMODELSFCODE = "PSMODELSFCODE"; // 模型后台代码
	public final static String PSDEPSLN = "PSDEPSLN"; // 部署方案
	public final static String PSDELOGICLINK = "PSDELOGICLINK"; // 实体处理逻辑连接
	public final static String PSDEVSLNSYSTS = "PSDEVSLNSYSTS"; // 开发系统任务加载
	public final static String PSPFCTRLTEMPL = "PSPFCTRLTEMPL"; // 云应用部件代码模版
	public final static String PSSYSCTRLSTYLE = "PSSYSCTRLSTYLE"; // 系统部件样式
	public final static String PSSYSTEMAS = "PSSYSTEMAS"; // 系统应用服务器
	public final static String PSDEDATARELATION = "PSDEDATARELATION"; // 实体关系界面组
	public final static String PSSFCODETYPE = "PSSFCODETYPE"; // 后台技术架构框架代码
	public final static String PSSYSBACKSERVICE = "PSSYSBACKSERVICE"; // 系统后台任务
	public final static String PSMODELAPIMETHOD = "PSMODELAPIMETHOD"; // 平台API接口方法
	public final static String PSPFSTYLELOG = "PSPFSTYLELOG"; // 前台技术架构框架变更
	public final static String PSSYSRUNSESSION = "PSSYSRUNSESSION"; // 系统运行会话
	public final static String PSSFACHANDLER = "PSSFACHANDLER"; // 系统服务部件处理器
	public final static String PSSYSDSACTION = "PSSYSDSACTION"; // 系统开发操作
	public final static String PSDEFDTCOL = "PSDEFDTCOL"; // 属性数据列
	public final static String PSPORTLETTYPE = "PSPORTLETTYPE"; // 平台门户部件类型
	public final static String PSDEAWITEM = "PSDEAWITEM"; // 实体操作向导项
	public final static String PSDEFVRTYPEDETAIL = "PSDEFVRTYPEDETAIL"; // 云实体属性值规则类型明细
	public final static String PSDEVSYSDIFFITEM = "PSDEVSYSDIFFITEM"; // 云应用系统差异项
	public final static String PSDELOGICPARAM = "PSDELOGICPARAM"; // 实体逻辑参数
	public final static String PSDEPSLNMODE = "PSDEPSLNMODE"; // 部署方案模式
	public final static String PSSYSTDITEM = "PSSYSTDITEM"; // 系统测试数据项
	public final static String PSDEVSLNSYSVER = "PSDEVSLNSYSVER"; // 开发系统版本
	public final static String PSSYSDATASYNCAGENT = "PSSYSDATASYNCAGENT"; // 系统数据同步代理
	public final static String PSSYSPOLICYMODEL = "PSSYSPOLICYMODEL"; // 平台系统策略模型项
	public final static String PSDEMAINSTATE = "PSDEMAINSTATE"; // 实体主状态
	public final static String PSDEDBCFG = "PSDEDBCFG"; // 实体数据库配置
	public final static String PSWFLINKROLE = "PSWFLINKROLE"; // 流程处理连接角色
	public final static String PSDEACTION = "PSDEACTION"; // 实体行为
	public final static String PSDEPSLNDBINST = "PSDEPSLNDBINST"; // 部署方案数据库实例
	public final static String PSSUBDEVIEW = "PSSUBDEVIEW"; // 子系统实体视图
	public final static String PSAPPVIEWLOGIC = "PSAPPVIEWLOGIC"; // 视图逻辑
	public final static String PSSYSSFPUBPKG = "PSSYSSFPUBPKG"; // 后台服务体系组件
	public final static String PSLANGUAGEITEM = "PSLANGUAGEITEM"; // 语言定义项
	public final static String PSDEFVRTYPE = "PSDEFVRTYPE"; // 云实体属性值规则类型
	public final static String PSSYSBDSCHEME = "PSSYSBDSCHEME"; // 系统大数据体系
	public final static String PSDEACMODEITEM = "PSDEACMODEITEM"; // 实体自填数据项
	public final static String PSFORMDETAILTYPE = "PSFORMDETAILTYPE"; // 平台表单成员类型
	public final static String PSSYSWFSETTING = "PSSYSWFSETTING"; // 系统流程配置
	public final static String PSBDTYPE = "PSBDTYPE"; // 大数据库类型
	public final static String PSDEJOINTYPE = "PSDEJOINTYPE"; // 云实体查询连接类型
	public final static String PSMQINST = "PSMQINST"; // 平台MQ实例
	public final static String PSDEVSLNUSER = "PSDEVSLNUSER"; // 开发方案用户
	public final static String PSVALUERULE = "PSVALUERULE"; // 平台值规则
	public final static String PSDEGCTYPE = "PSDEGCTYPE"; // 云实体表格列类型
	public final static String PSSYSOPPRIV = "PSSYSOPPRIV"; // 系统权限标识
	public final static String PSPRODUCTTYPE = "PSPRODUCTTYPE"; // 平台产品类型
	public final static String PSSYSWFMODE = "PSSYSWFMODE"; // 系统工作流模式
	public final static String PSSYSSAMPLEVALUE = "PSSYSSAMPLEVALUE"; // 系统示例值
	public final static String PSDEDATAEXP = "PSDEDATAEXP"; // 实体数据导出
	public final static String PSVIEWENGINE = "PSVIEWENGINE"; // 视图引擎
	public final static String PSWXLOGIC = "PSWXLOGIC"; // 微信交互逻辑
	public final static String PSSYSDBCHGLOG = "PSSYSDBCHGLOG"; // 系统模型变更日志
	public final static String PSPFPKG = "PSPFPKG"; // 应用组件包
	public final static String PSPFPKGVER = "PSPFPKGVER"; // 前端应用组件包版本
	public final static String PSSYSCOUNTERITEM = "PSSYSCOUNTERITEM"; // 系统计数器项
	public final static String PSDEUAGRPDETAIL = "PSDEUAGRPDETAIL"; // 实体界面行为组成员
	public final static String PSAPPDEUAGRPDETAIL = "PSAPPDEUAGRPDETAIL"; // 应用实体界面行为组成员
	public final static String PSSYSAPPDEUAGRPDETAIL = "PSSYSAPPDEUAGRPDETAIL"; // 全局应用实体界面行为组成员
	public final static String PSHELPSECTIONTYPE = "PSHELPSECTIONTYPE"; // 帮助文章章节类型
	public final static String PSDEACTIONLOGIC = "PSDEACTIONLOGIC"; // 实体行为逻辑
	public final static String PSPFSTYLE = "PSPFSTYLE"; // 应用样式
	public final static String PSAPPEDITORTEMPL = "PSAPPEDITORTEMPL"; // 应用编辑器模版
	public final static String PSMODELHOTCODE = "PSMODELHOTCODE"; // 系统模型热代码
	public final static String PSSYSBDTABLE = "PSSYSBDTABLE"; // 大数据库表
	public final static String PSHELPARTSEC = "PSHELPARTSEC"; // 帮助文章预置章节
	public final static String PSVTCTRL = "PSVTCTRL"; // 平台视图类型部件
	public final static String PSDBVALUEMODE = "PSDBVALUEMODE"; // 数据库值模式
	public final static String PSAPPFUNC = "PSAPPFUNC"; // 应用功能
	public final static String PSVIEWSTYLE = "PSVIEWSTYLE"; // 平台视图样式
	public final static String PSDECHARTPARAM = "PSDECHARTPARAM"; // 实体图表数据序列
	public final static String PSDEREPITEM = "PSDEREPITEM"; // 实体报表项
	public final static String PSTREENODETYPE = "PSTREENODETYPE"; // 平台树节点类型
	public final static String PSCSSTEMPL = "PSCSSTEMPL"; // 平台界面样式表模板
	public final static String PSDEFINPUTTIP = "PSDEFINPUTTIP"; // 属性输入提示
	public final static String PSV3MIGRATEDE = "PSV3MIGRATEDE"; // 平台V3迁移实体
	public final static String PSPFSTYLEPRJ = "PSPFSTYLEPRJ"; // 前端应用样式项目
	public final static String PSASBOOKINGLOG = "PSASBOOKINGLOG"; // 平台应用容器预约日志
	public final static String PSSYSACHANDLER = "PSSYSACHANDLER"; // 平台部件处理器
	public final static String PSSYSMSGTEMPL = "PSSYSMSGTEMPL"; // 系统消息模板
	public final static String PSCODEITEM = "PSCODEITEM"; // 系统代码表项
	public final static String PSFDLOGICTYPE = "PSFDLOGICTYPE"; // 平台表单成员逻辑类型
	public final static String PSWXENTAPP = "PSWXENTAPP"; // 微信企业应用
	public final static String PSSUBDE = "PSSUBDE"; // 平台子系统实体
	public final static String PSDEUIACTIONTYPE = "PSDEUIACTIONTYPE"; // 云实体界面行为类型
	public final static String PSVIEWTYPECAT = "PSVIEWTYPECAT"; // 平台视图类型分类
	public final static String PSSFCONFIG = "PSSFCONFIG"; // 系统服务框架配置
	public final static String PSV3MGGRID = "PSV3MGGRID"; // 平台V3迁移表格
	public final static String PSCOREPRDFUNC = "PSCOREPRDFUNC"; // 平台核心产品功能
	public final static String PSSYSUNIT = "PSSYSUNIT"; // 系统单位
	public final static String PSPDTAPPFUNC = "PSPDTAPPFUNC"; // 平台预置应用功能
	public final static String PSDEVIEWRV = "PSDEVIEWRV"; // 实体视图关联视图
	public final static String PSSYSDICTCAT = "PSSYSDICTCAT"; // 系统输入词条类别
	public final static String PSTASKSERVER = "PSTASKSERVER"; // 平台任务服务器
	public final static String PSVIEWTYPELOGIC = "PSVIEWTYPELOGIC"; // 云视图类型内置逻辑
	public final static String PSAPPUITHEME = "PSAPPUITHEME"; // 应用界面主题
	public final static String PSAPPLAN = "PSAPPLAN"; // 应用多语言
	public final static String PSSYSLAN = "PSSYSLAN"; // 系统多语言
	public final static String PSDEFSFITEM = "PSDEFSFITEM"; // 实体属性搜索项
	public final static String PSDEFSEARCHMODE = "PSDEFSEARCHMODE"; // 实体属性搜索模式
	public final static String PSHELPMODART = "PSHELPMODART"; // 帮助模块文章
	public final static String PSDCBKTASK = "PSDCBKTASK"; // 云应用中心后台任务
	public final static String PSDCDBPROC = "PSDCDBPROC"; // 应用中心数据库过程
	public final static String PSV3MGVIEW = "PSV3MGVIEW"; // 平台V3默认视图
	public final static String PSSVNINSTREPO = "PSSVNINSTREPO"; // 平台SVN仓库
	public final static String PSAPPPKG = "PSAPPPKG"; // 系统应用组件包
	public final static String PSASTYPE = "PSASTYPE"; // 应用服务器类型
	public final static String PSDEDSDQ = "PSDEDSDQ"; // 实体数据集合查询
	public final static String PSDBSPPARTTEMPL = "PSDBSPPARTTEMPL"; // 数据库系统过程成员模版
	public final static String PSSYSDEVBKTASK = "PSSYSDEVBKTASK"; // 系统开发后台任务
	public final static String PSDETBITEM = "PSDETBITEM"; // 实体工具栏项
	public final static String PSDEPSLNMODEPRD = "PSDEPSLNMODEPRD"; // 部署方案产品部署
	public final static String PSDEVSLNSYS = "PSDEVSLNSYS"; // 开发系统
	public final static String PSSYSVALUERULE = "PSSYSVALUERULE"; // 系统值规则
	public final static String PSSYSPFPITEMPL = "PSSYSPFPITEMPL"; // 系统应用插件模板
	public final static String PSDEVRGRPDETAIL = "PSDEVRGRPDETAIL"; // 实体属性值规则组成员
	public final static String PSAPPCTRLSTYLE = "PSAPPCTRLSTYLE"; // 应用部件样式
	public final static String PSROSSERVER = "PSROSSERVER"; // 云ROS服务器
	public final static String PSDEDRITEM = "PSDEDRITEM"; // 实体关系界面
	public final static String PSDEACTIONTYPE = "PSDEACTIONTYPE"; // 云实体行为类型
	public final static String PSCOREPRDVER = "PSCOREPRDVER"; // 平台核心产品版本
	public final static String PSPFVIEWTEMPL = "PSPFVIEWTEMPL"; // 应用视图代码模版
	public final static String PSSYSTASK = "PSSYSTASK"; // TODO任务
	public final static String PSVTSAMPLE = "PSVTSAMPLE"; // 视图类型示例
	public final static String PSDBVFCODE = "PSDBVFCODE"; // 数据库值函数代码
	public final static String PSDELNPARAM = "PSDELNPARAM"; // 实体处理逻辑节点参数
	public final static String PSSVRSERVER = "PSSVRSERVER"; // 平台系统主机
	public final static String PSDECHARTAXES = "PSDECHARTAXES"; // 实体图像维度
	public final static String PSUNKNOWN = "PSUNKNOWN"; // 未知模型接口
	public final static String PSTASKSERVERLOG = "PSTASKSERVERLOG"; // 任务服务器日志
	public final static String PSSUBSYSSADETAIL = "PSSUBSYSSADETAIL"; // 子系统服务接口成员
	public final static String PSSVRDOMAIN = "PSSVRDOMAIN"; // 平台服务域
	public final static String PSHELPRESOURCE = "PSHELPRESOURCE"; // 帮助资源
	public final static String PSAPPUSERMODE = "PSAPPUSERMODE"; // 应用用户模式
	public final static String PSDERDEFMAP = "PSDERDEFMAP"; // 实体关系属性映射
	public final static String PSCTRLMSGITEM = "PSCTRLMSGITEM"; // 部件消息项
	public final static String PSDEVCENTERDBINST = "PSDEVCENTERDBINST"; // 云应用中心数据库实例
	public final static String PSHELPARTICLETEMPL = "PSHELPARTICLETEMPL"; // 帮助文章模板
	public final static String PSCODELISTTEMPL = "PSCODELISTTEMPL"; // 平台代码表模版
	public final static String PSSFSTYLECODE = "PSSFSTYLECODE"; // 系统服务框架宏
	public final static String PSPDTVIEW = "PSPDTVIEW"; // 平台预置视图
	public final static String PSDEFVRDSPARAM = "PSDEFVRDSPARAM"; // 实体属性值规则参数
	public final static String PSDEVCENTERMQ = "PSDEVCENTERMQ"; // 云应用中心MQ服务
	public final static String PSDESPCODEPART = "PSDESPCODEPART"; // 系统存储过程代码块
	public final static String PSDEVCENTERTS = "PSDEVCENTERTS"; // 云应用中心任务服务器
	public final static String PSSYSUSERDR = "PSSYSUSERDR"; // 系统自定义数据范围
	public final static String PSSYSOUTYPE = "PSSYSOUTYPE"; // 系统组织单元类型
	public final static String PSV3MIGRATE = "PSV3MIGRATE"; // 平台V3迁移
	public final static String PSSFSTYLE = "PSSFSTYLE"; // 服务框架
	public final static String PSSYSDEVINFOTYPE = "PSSYSDEVINFOTYPE"; // 云系统开发信息类型
	public final static String PSSYSTCINPUT = "PSSYSTCINPUT"; // 系统测试用例输入
	public final static String PSSYSTCINPUT2 = "PSSYSTCINPUT2"; // 系统测试用例输入（有测试项目）
	public final static String PSSYSTCASSERT = "PSSYSTCASSERT"; // 系统测试用例断言
	public final static String PSSYSTCASSERT2 = "PSSYSTCASSERT2"; // 系统测试用例断言（有测试项目）
	public final static String PSDATASYNCAGENTTYPE = "PSDATASYNCAGENTTYPE"; // 数据同步代理类型
	public final static String PSSYSLANITEM = "PSSYSLANITEM"; // 平台语言项
	public final static String PSDEDSCODE = "PSDEDSCODE"; // 实体数据集合代码
	public final static String PSDCPRODUCT = "PSDCPRODUCT"; // 云应用中心产品
	public final static String PSDEDQPDCOND = "PSDEDQPDCOND"; // 云实体数据查询预置条件
	public final static String PSSYSISSUEENGINE = "PSSYSISSUEENGINE"; // 云系统问题分析引擎
	public final static String PSDCSFPKG = "PSDCSFPKG"; // 云应用中心服务框架组件包
	public final static String PSDEVUSER = "PSDEVUSER"; // 云应用中心用户
	public final static String PSMIDETAIL = "PSMIDETAIL"; // 云模型初始化步骤
	public final static String PSDEPSLNPRD = "PSDEPSLNPRD"; // 部署方案产品
	public final static String PSAPPFUNCTYPE = "PSAPPFUNCTYPE"; // 云应用功能类型
	public final static String PSPFPLUGINTYPE = "PSPFPLUGINTYPE"; // 应用框架插件类型
	public final static String PSEDITORTYPE = "PSEDITORTYPE"; // 平台编辑器类型
	public final static String PSSVRPROVIDER = "PSSVRPROVIDER"; // 云服务提供商
	public final static String PSDCBKTYPE = "PSDCBKTYPE"; // 云应用中心后台任务类型
	public final static String PSMODELRS = "PSMODELRS"; // 系统模型关系
	public final static String PSWFSUBWF = "PSWFSUBWF"; // 流程子流程
	public final static String PSDEFDATATYPE = "PSDEFDATATYPE"; // 云实体属性数据类型
	public final static String PSDEFVRCODETYPE = "PSDEFVRCODETYPE"; // 平台属性规则代码类型
	public final static String PSSFSTYLELOG = "PSSFSTYLELOG"; // 服务框架变更
	public final static String PSDESPFIELD = "PSDESPFIELD"; // 系统存储过程属性
	public final static String PSPFSTYLEPKG = "PSPFSTYLEPKG"; // 前端应用样式组件包
	public final static String PSMODELREF = "PSMODELREF"; // 模型引用
	public final static String PSHELPSECTIONTEMPL = "PSHELPSECTIONTEMPL"; // 帮助章节模板
	public final static String PSDEFFORMITEM = "PSDEFFORMITEM"; // 实体属性界面配置
	public final static String PSAPPDEFFORMITEM = "PSAPPDEFFORMITEM"; // 应用实体属性表单项
	public final static String PSSYSREQMODULE = "PSSYSREQMODULE"; // 系统需求模块
	public final static String PSDRITEMTYPE = "PSDRITEMTYPE"; // 平台数据关系项类型
	public final static String PSSYSDEVBTTYPE = "PSSYSDEVBTTYPE"; // 云系统开发后台任务类型
	public final static String PSSUBSYSSERVICEAPI = "PSSUBSYSSERVICEAPI"; // 子系统服务接口
	public final static String PSDCSYSPRODUCT = "PSDCSYSPRODUCT"; // 云应用中心系统产品
	public final static String PSDECTRL = "PSDECTRL"; // 实体部件配置
	public final static String PSDEPSLNRUNLOG = "PSDEPSLNRUNLOG"; // 部署方案运行日志
	public final static String PSSYSBDPART = "PSSYSBDPART"; // 大数据分区
	public final static String PSSYSTOOLBAR = "PSSYSTOOLBAR"; // 平台预置工具栏
	public final static String PSDEDRGROUP = "PSDEDRGROUP"; // 实体关系界面分组
	public final static String PSDEDQCOND = "PSDEDQCOND"; // 实体数据查询条件
	public final static String PSCPVFUNC = "PSCPVFUNC"; // 平台核心产品版本功能
	public final static String PSDEFGRIDCOL = "PSDEFGRIDCOL"; // 实体属性表格列
	public final static String PSDCDBFUNC = "PSDCDBFUNC"; // 应用中心数据库函数
	public final static String PSDEFIUDETAIL = "PSDEFIUDETAIL"; // 实体表单项更新明细
	public final static String PSWXMENUITEM = "PSWXMENUITEM"; // 微信菜单项
	public final static String PSDEVRGROUP = "PSDEVRGROUP"; // 实体属性值规则组
	public final static String PSDEVSLNSYSKEY = "PSDEVSLNSYSKEY"; // 开发系统访问标识
	public final static String PSDEVCENTERRES = "PSDEVCENTERRES"; // 云应用中心资源
	public final static String PSCTRLTYPEACTION = "PSCTRLTYPEACTION"; // 平台部件操作
	public final static String PSSUBSYSDM = "PSSUBSYSDM"; // 子系统数据库结构
	public final static String PSDEVUSERRECENT = "PSDEVUSERRECENT"; // 云应用用户最近访问
	public final static String PSSYSTEMDBCFG = "PSSYSTEMDBCFG"; // 系统数据库
	public final static String PSSYSPRDVER = "PSSYSPRDVER"; // 云系统商品版本
	public final static String PSWXMENU = "PSWXMENU"; // 微信菜单
	public final static String PSSAMPLEVALUE = "PSSAMPLEVALUE"; // 平台示例值
	public final static String PSBDSERVER = "PSBDSERVER"; // 平台大数据服务器
	public final static String PSWXACCOUNT = "PSWXACCOUNT"; // 微信公众号
	public final static String PSSYSDMITEM = "PSSYSDMITEM"; // 系统数据库模型项
	public final static String PSSYSTASKDATA = "PSSYSTASKDATA"; // 系统开发任务讨论
	public final static String PSWFPROCPARAM = "PSWFPROCPARAM"; // 流程处理参数
	public final static String PSWFPROCROLE = "PSWFPROCROLE"; // 流程处理角色
	public final static String PSDEVENV = "PSDEVENV"; // 云开发环境
	public final static String PSDELISTITEM = "PSDELISTITEM"; // 实体列表项
	public final static String PSSYSSFCODE = "PSSYSSFCODE"; // 系统服务自定义代码
	public final static String PSDESYSPROC = "PSDESYSPROC"; // 实体系统存储过程
	public final static String PSSYSMODELVER = "PSSYSMODELVER"; // 云系统模型版本
	public final static String PSSFPKGCAT = "PSSFPKGCAT"; // 服务框架包分类
	public final static String PSHELPPRJ = "PSHELPPRJ"; // 系统帮助项目
	public final static String PSSYSIMAGE = "PSSYSIMAGE"; // 系统图片资源
	public final static String PSSUBAPP = "PSSUBAPP"; // 平台子系统应用
	public final static String PSBACKSERVICE = "PSBACKSERVICE"; // 平台预置后台任务
	public final static String PSAPPVIEWSTYLE = "PSAPPVIEWSTYLE"; // 应用视图样式（已废弃）
	public final static String PSDEDBINDEX = "PSDEDBINDEX"; // 实体数据库索引
	public final static String PSCTRLTYPE = "PSCTRLTYPE"; // 平台部件类型
	public final static String PSAPPPORTALVIEW = "PSAPPPORTALVIEW"; // 应用门户视图
	public final static String PSSYSDEVINFO = "PSSYSDEVINFO"; // 系统开发信息
	public final static String PSDCSYSPRDVER = "PSDCSYSPRDVER"; // 云应用中心系统产品版本
	public final static String PSSYSREQITEMDATA = "PSSYSREQITEMDATA"; // 需求项讨论
	public final static String PSAPPVIEWCODE = "PSAPPVIEWCODE"; // 系统应用自定义代码
	public final static String PSUNIT = "PSUNIT"; // 平台预置单位
	public final static String PSSYSREFDE = "PSSYSREFDE"; // 系统引用实体
	public final static String PSSYSBDTABLERS = "PSSYSBDTABLERS"; // 大数据表关系
	public final static String PSDER_DER11 = "PSDER_DER11"; // 实体关系（1:1）
	public final static String PSDER_DERCUSTOM = "PSDER_DERCUSTOM"; // 实体关系（自定义）
	public final static String PSDER_DERAGGDATA = "PSDER_DERAGGDATA"; // 实体关系（聚合数据）
	public final static String PSSUBSYSVER = "PSSUBSYSVER"; // 平台子系统版本
	public final static String PSDEGEIUPDATE = "PSDEGEIUPDATE"; // 表格编辑项更新模式
	public final static String PSMODELAPIRS = "PSMODELAPIRS"; // 系统模型API关系
	public final static String PSSYSCSSCAT = "PSSYSCSSCAT"; // 系统界面样式表分类
	public final static String PSHELPSECTION = "PSHELPSECTION"; // 帮助章节
	public final static String PSDETREENODERV = "PSDETREENODERV"; // 树节点关联视图
	public final static String PSWFDE = "PSWFDE"; // 工作流实体
	public final static String PSDEDUPRULE = "PSDEDUPRULE"; // 实体数据重复规则
	public final static String PSSYSMODELFUNCTEMPL = "PSSYSMODELFUNCTEMPL"; // 系统模型功能模板实现
	public final static String PSPFPLUGINTEMPL = "PSPFPLUGINTEMPL"; // 平台预置应用框架插件模板
	public final static String PSAPPUTILPAGE = "PSAPPUTILPAGE"; // 应用功能页面
	public final static String PSSFSTYLEVER = "PSSFSTYLEVER"; // 服务框架扩展
	public final static String PSSUBDEACTION = "PSSUBDEACTION"; // 平台子实体操作
	public final static String PSVTSTYLE = "PSVTSTYLE"; // 平台视图类型样式
	public final static String PSSYSEDITORSTYLE = "PSSYSEDITORSTYLE"; // 系统编辑器样式
	public final static String PSVIEWLOGICTYPE = "PSVIEWLOGICTYPE"; // 云视图预置逻辑
	public final static String PSSFVERCODE = "PSSFVERCODE"; // 系统服务扩展代码模板
	public final static String PSPFCTDETAIL = "PSPFCTDETAIL"; // 云应用部件代码模版成员
	public final static String PSSYSDEPLOYDB = "PSSYSDEPLOYDB"; // 系统部署数据库
	public final static String PSDEVSERVER = "PSDEVSERVER"; // 平台开发主机
	public final static String PSSYSDBVFCODE = "PSSYSDBVFCODE"; // 系统数据库值函数代码
	public final static String PSDCCOREPRDISSUE = "PSDCCOREPRDISSUE"; // 云应用中心核心产品问题
	public final static String PSWFPROCESS = "PSWFPROCESS"; // 流程处理
	public final static String PSSFVERCODEITEM = "PSSFVERCODEITEM"; // 系统服务框架版本代码项
	public final static String PSDER_DERMULINH = "PSDER_DERMULINH"; // 实体关系（多继承）
	public final static String PSSYSSERVICEAPI = "PSSYSSERVICEAPI"; // 系统服务接口
	public final static String PSSYSISSUE = "PSSYSISSUE"; // 系统问题
	public final static String PSDEVUSEROBJ = "PSDEVUSEROBJ"; // 云应用中心用户对象
	public final static String PSSYSREQITEM = "PSSYSREQITEM"; // 系统需求项
	public final static String PSDEVCENTERSF = "PSDEVCENTERSF"; // 云应用中心服务框架
	public final static String PSSYSPFPLUGIN = "PSSYSPFPLUGIN"; // 应用框架插件
	public final static String PSCTRLMSG = "PSCTRLMSG"; // 部件消息
	public final static String PSDBVALUEOP = "PSDBVALUEOP"; // 数据库值操作符
	public final static String PSDEPSLNASGRP = "PSDEPSLNASGRP"; // 部署方案应用服务器组
	public final static String PSAPPSERVER = "PSAPPSERVER"; // 平台应用服务器
	public final static String PSSFSTYLEPRJ = "PSSFSTYLEPRJ"; // 服务框架项目
	public final static String PSDEDQJOIN = "PSDEDQJOIN"; // 实体数据查询连接
	public final static String PSDEPSLNAS = "PSDEPSLNAS"; // 部署方案应用服务器
	public final static String PSMODELINIT = "PSMODELINIT"; // 云模型初始化配置
	public final static String PSDEFORM = "PSDEFORM"; // 实体表单
	public final static String PSSYSISSUETYPE = "PSSYSISSUETYPE"; // 云系统问题类型
	public final static String PSCOUNTER = "PSCOUNTER"; // 平台预置计数器
	public final static String PSIMAGETEMPL = "PSIMAGETEMPL"; // 平台图片模版
	public final static String PSDEDBOBJSQL = "PSDEDBOBJSQL"; // 实体数据库对象代码
	public final static String PSDECHART = "PSDECHART"; // 实体图表
	public final static String PSSYSUSERMODE = "PSSYSUSERMODE"; // 系统用户模式
	public final static String PSSUBSYSSF = "PSSUBSYSSF"; // 平台子系统服务体系
	public final static String PSMODELAPI = "PSMODELAPI"; // 平台API
	public final static String PSSFPKGVER = "PSSFPKGVER"; // 服务框架组件版本
	public final static String PSCOREPRDCAT = "PSCOREPRDCAT"; // 平台核心产品分类
	public final static String PSDER_DER1N = "PSDER_DER1N"; // 实体关系（1:N）
	public final static String PSDESADETAIL = "PSDESADETAIL"; // 实体服务接口成员
	public final static String PSSYSPRODUCT = "PSSYSPRODUCT"; // 平台系统产品
	public final static String PSSYSACTOR = "PSSYSACTOR"; // 系统角色
	public final static String PSACHANDLER = "PSACHANDLER"; // 部件后台处理
	public final static String PSACHANDLERACTION = "PSACHANDLERACTION"; // 部件后台处理行为
	public final static String PSDEVCENTERLOG = "PSDEVCENTERLOG"; // 云应用中心日志
	public final static String PSSYSRUNLOG = "PSSYSRUNLOG"; // 系统运行日志
	public final static String PSDEVUSERMODEL = "PSDEVUSERMODEL"; // 用户访问模型
	public final static String PSAPPMENU = "PSAPPMENU"; // 应用菜单
	public final static String PSDEGRID = "PSDEGRID"; // 实体表格
	public final static String PSVIEWTYPE = "PSVIEWTYPE"; // 平台视图类型
	public final static String PSDBDEVINST = "PSDBDEVINST"; // 平台数据库开发实例
	public final static String PSHELPARTICLETYPE = "PSHELPARTICLETYPE"; // 帮助文章类型
	public final static String PSDEVCENTERSERVER = "PSDEVCENTERSERVER"; // 云应用中心主机
	public final static String PSTSCMD = "PSTSCMD"; // 任务服务器后台命令
	public final static String PSDEPSLNASITEM = "PSDEPSLNASITEM"; // 部署方案应用服务器组成员
	public final static String PSDEUAGROUP = "PSDEUAGROUP"; // 实体界面行为组
	public final static String PSAPPDEUAGROUP = "PSAPPDEUAGROUP"; // 应用实体界面行为组
	public final static String PSSYSAPPDEUAGROUP = "PSSYSAPPDEUAGROUP"; // 全局应用实体界面行为组
	public final static String PSDCDBTABLE = "PSDCDBTABLE"; // 应用中心数据库表
	public final static String PSSFEXCEPTION = "PSSFEXCEPTION"; // 系统服务体系异常对象
	public final static String PSDELOGICNODE = "PSDELOGICNODE"; // 实体处理逻辑节点
	public final static String PSPFEDITORTEMPL = "PSPFEDITORTEMPL"; // 前台编辑器模版
	public final static String PSDEVSYSDIFFREP = "PSDEVSYSDIFFREP"; // 开发系统差异分析
	public final static String PSSVNSERVER = "PSSVNSERVER"; // 云SVN服务器
	public final static String PSDELLCOND = "PSDELLCOND"; // 实体处理逻辑连接条件
	public final static String PSCOUNTERTYPESF = "PSCOUNTERTYPESF"; // 平台计数器类型服务框架
	public final static String PSDBSERVER = "PSDBSERVER"; // 平台数据库主机
	public final static String PSSYSTESTDATA = "PSSYSTESTDATA"; // 系统测试数据
	public final static String PSCSSCATTEMPL = "PSCSSCATTEMPL"; // 平台样式表分类模板
	public final static String PSSYSUNIRES = "PSSYSUNIRES"; // 系统统一资源
	public final static String PSDEPSLNLOG = "PSDEPSLNLOG"; // 部署方案操作日志
	public final static String PSDCDBSEQU = "PSDCDBSEQU"; // 应用中心数据库序列
	public final static String PSSYSDEPLOY = "PSSYSDEPLOY"; // 系统部署
	public final static String PSSYSDSACTIONTYPE = "PSSYSDSACTIONTYPE"; // 云系统开发环境操作类型
	public final static String PSDEDQCODE = "PSDEDQCODE"; // 数据数据查询代码
	public final static String PSCOUNTERTYPE = "PSCOUNTERTYPE"; // 平台计数器类型
	public final static String PSCTRLEVENT = "PSCTRLEVENT"; // 云控件事件
	public final static String PSDCBULLETIN = "PSDCBULLETIN"; // 云应用中心公告
	public final static String PSSFSTYLEPKG = "PSSFSTYLEPKG"; // 服务框架样式组件
	public final static String PSVIEWWIZARDGROUP = "PSVIEWWIZARDGROUP"; // 视图向导组
	public final static String PSCTRLTYPEEVENT = "PSCTRLTYPEEVENT"; // 平台部件事件
	public final static String PSDEVSERVERLEASE = "PSDEVSERVERLEASE"; // 云开发主机租约
	public final static String PSDCMTDEF = "PSDCMTDEF"; // 模型模板预置属性
	public final static String PSDEUIACTION = "PSDEUIACTION"; // 实体界面行为
	public final static String PSLANGUAGERES = "PSLANGUAGERES"; // 语言资源
	public final static String PSDEMSACTION = "PSDEMSACTION"; // 实体主状态操作
	public final static String PSSYSBDTABLEDE = "PSSYSBDTABLEDE"; // 大数据表实体关系
	public final static String PSVIEWMSG = "PSVIEWMSG"; // 视图消息
	public final static String PSDCTASKLOG = "PSDCTASKLOG"; // 云应用中心后台作业日志
	public final static String PSPFVLTEMPL = "PSPFVLTEMPL"; // 云视图逻辑模版
	public final static String PSROBOT = "PSROBOT"; // 平台机器人
	public final static String PSDESERVICEAPI = "PSDESERVICEAPI"; // 实体服务接口
	public final static String PSSYSERMAP = "PSSYSERMAP"; // 系统ER图
	public final static String PSSYSUCMAP = "PSSYSUCMAP"; // 系统UC图
	public final static String PSDEDQCODECOND = "PSDEDQCODECOND"; // 实体查询代码条件
	public final static String PSHELPARTICLE = "PSHELPARTICLE"; // 帮助文章
	public final static String PSPORTLET = "PSPORTLET"; // 平台预置门户部件
	public final static String PSSYSTEMRUN = "PSSYSTEMRUN"; // 系统运行
	public final static String PSSYSPOLICY = "PSSYSPOLICY"; // 平台系统策略
	public final static String PSWFLINK = "PSWFLINK"; // 流程处理连接
	public final static String PSV3MGFORM = "PSV3MGFORM"; // 平台V3迁移表单
	public final static String PSSYSLANRES = "PSSYSLANRES"; // 平台语言资源
	public final static String PSAPPVIEWREF = "PSAPPVIEWREF"; // 应用视图引用
	public final static String PSDEVSLN = "PSDEVSLN"; // 开发方案
	public final static String PSDCBDINST = "PSDCBDINST"; // 云应用中心大数据库实例
	public final static String PSVTRV = "PSVTRV"; // 平台视图类型关联视图
	public final static String PSDCSYSRES = "PSDCSYSRES"; // 云应用中心系统资源
	public final static String PSDEWIZARD = "PSDEWIZARD"; // 实体向导
	public final static String PSSYSMODELFUNC = "PSSYSMODELFUNC"; // 系统模型功能
	public final static String PSSYSREQITEMHIS = "PSSYSREQITEMHIS"; // 需求项备份
	public final static String PSMOBAPPPACK = "PSMOBAPPPACK"; // 移动应用打包
	public final static String PSWFLINKCOND = "PSWFLINKCOND"; // 流程处理连接条件
	public final static String PSSYSTEMMQ = "PSSYSTEMMQ"; // 系统MQ
	public final static String PSPFPLUGIN = "PSPFPLUGIN"; // 平台预置应用框架插件
	public final static String PSDEVCENTERSRV = "PSDEVCENTERSRV"; // 云应用中心服务
	public final static String PSSYSDBDETAIL = "PSSYSDBDETAIL"; // 系统数据库发布版本
	public final static String PSDEMAPDETAIL = "PSDEMAPDETAIL"; // 实体映射属性
	public final static String PSSTUDIOSERVER = "PSSTUDIOSERVER"; // 云开发工具服务器
	public final static String PSSYSPDTVIEW = "PSSYSPDTVIEW"; // 系统预置视图
	public final static String PSVARTYPE = "PSVARTYPE"; // 平台变量类型
	public final static String PSDEFIUPDATE = "PSDEFIUPDATE"; // 实体表单项更新
	public final static String PSWFPROCESSTYPE = "PSWFPROCESSTYPE"; // 云系统流程处理类型
	public final static String PSWFWORKTIME = "PSWFWORKTIME"; // 流程工作时间
	public final static String PSAPPMODULE = "PSAPPMODULE"; // 应用模块
	public final static String PSSUBAPPVIEW = "PSSUBAPPVIEW"; // 平台子系统应用视图
	public final static String PSWFLINKTYPE = "PSWFLINKTYPE"; // 云系统流程连接类型
	public final static String PSSUBVIEWTYPE = "PSSUBVIEWTYPE"; // 系统视图样式
	public final static String PSUAWIZARD = "PSUAWIZARD"; // 实体界面操作向导
	public final static String PSVIEWMSGGRPDETAIL = "PSVIEWMSGGRPDETAIL"; // 视图消息成员
	public final static String PSDEDSPARAM = "PSDEDSPARAM"; // 实体数据集合参数
	public final static String PSSYSMODELINST = "PSSYSMODELINST"; // 云系统模型实例
	public final static String PSDEFORMDETAIL = "PSDEFORMDETAIL"; // 实体表单成员
	public final static String PSDBPROCPARAM = "PSDBPROCPARAM"; // 系统存储过程参数
	public final static String PSDCSERVER = "PSDCSERVER"; // 平台中心服务器
	public final static String PSDEGRIDCOL = "PSDEGRIDCOL"; // 实体表格列
	public final static String PSSFCODETEMPL = "PSSFCODETEMPL"; // 系统服务代码模版
	public final static String PSWFPROCSUBWF = "PSWFPROCSUBWF"; // 流程处理子流程
	public final static String PSDEDATASYNC = "PSDEDATASYNC"; // 实体数据同步
	public final static String PSPFAPPTEMPL = "PSPFAPPTEMPL"; // 云应用应用代码模版
	public final static String PSDCDBOBJ = "PSDCDBOBJ"; // 应用中心实例命令记录
	public final static String PSDEDQCODEEXP = "PSDEDQCODEEXP"; // 实体查询代码表达式
	public final static String PSHELPMODULE = "PSHELPMODULE"; // 帮助模块
	public final static String PSDEVSERVERTYPE = "PSDEVSERVERTYPE"; // 开发桌面类型
	public final static String PSMODELPFCODE = "PSMODELPFCODE"; // 模型前台代码
	public final static String PSAPPPVPART = "PSAPPPVPART"; // 应用门户视图部件
	public final static String PSDEGEIUDETAIL = "PSDEGEIUDETAIL"; // 表格编辑项更新成员
	public final static String PSSFPKG = "PSSFPKG"; // 服务框架组件包
	public final static String PSMODEL = "PSMODEL"; // 系统模型
	public final static String PSFORMTYPE = "PSFORMTYPE"; // 平台表单类型
	public final static String PSCTRLACTION = "PSCTRLACTION"; // 云控件行为
	public final static String PSSYSBDCOLUMN = "PSSYSBDCOLUMN"; // 大数据列
	public final static String PSDEFDLOGIC = "PSDEFDLOGIC"; // 实体表单成员逻辑项
	public final static String PSSYSTESTCASE = "PSSYSTESTCASE"; // 系统测试用例
	public final static String PSSYSTESTCASE2 = "PSSYSTESTCASE2"; // 系统测试用例（有项目）
	public final static String PSSYSTESTPRJ = "PSSYSTESTPRJ"; // 系统测试项目
	public final static String PSSYSTESTMODULE = "PSSYSTESTMODULE"; // 测试用例模块

	public final static String PSDETREENODERS = "PSDETREENODERS"; // 实体树节点关系
	public final static String PSSYSDEVSTUDIO = "PSSYSDEVSTUDIO"; // 系统开发用户
	public final static String PSDERTYPE = "PSDERTYPE"; // 实体关系类型
	public final static String PSSYSMODELLOG = "PSSYSMODELLOG"; // 系统模型变更
	public final static String PSSYSORGTYPE = "PSSYSORGTYPE"; // 系统组织类型
	public final static String PSSYSCOUNTER = "PSSYSCOUNTER"; // 系统计数器
	public final static String PSSUBSYS = "PSSUBSYS"; // 平台子系统
	public final static String PSDEVIEWCTRL = "PSDEVIEWCTRL"; // 实体视图部件
	public final static String PSDCMTDECAT = "PSDCMTDECAT"; // 模型模板实体分类
	public final static String PSDEVCENTERAS = "PSDEVCENTERAS"; // 云应用中心应用服务器
	public final static String PSAMITEMTYPE = "PSAMITEMTYPE"; // 云应用菜单项类型
	public final static String PSDEVCENTER = "PSDEVCENTER"; // 云应用中心
	public final static String PSEDITORSTYLE = "PSEDITORSTYLE"; // 平台预置编辑器样式
	public final static String PSBKTASKLOG = "PSBKTASKLOG"; // 平台后台任务日志
	public final static String PSLISTITEMTYPE = "PSLISTITEMTYPE"; // 平台列表项类型
	public final static String PSSYSDEPLOYAS = "PSSYSDEPLOYAS"; // 系统部署应用服务器
	public final static String PSVIEWMSGGROUP = "PSVIEWMSGGROUP"; // 视图消息组
	public final static String PSDER = "PSDER"; // 实体关系
	public final static String PSDCDBINDEX = "PSDCDBINDEX"; // 应用中心数据库索引
	public final static String PSDBOBJTYPE = "PSDBOBJTYPE"; // 平台数据库对象类型
	public final static String PSAPPUISTYLE = "PSAPPUISTYLE"; // 应用界面样式
	public final static String PSSYSREPORT = "PSSYSREPORT"; // 系统报表
	public final static String PSCOREPRD = "PSCOREPRD"; // 平台核心产品
	public final static String PSDEMODELCNT = "PSDEMODELCNT"; // 实体模型计数
	public final static String PSPFPUBCODE = "PSPFPUBCODE"; // 应用框架发布代码
	public final static String PSDEFTYPE = "PSDEFTYPE"; // 实体属性类型
	public final static String PSSF = "PSSF"; // 后台技术架构
	public final static String PSLANGUAGE = "PSLANGUAGE"; // 平台语言
	public final static String PSDEDATAIMP = "PSDEDATAIMP"; // 实体数据导入
	public final static String PSPRODUCT = "PSPRODUCT"; // 平台产品
	public final static String PSDEFIVR = "PSDEFIVR"; // 实体表单项值规则
	public final static String PSMODELAPIINT = "PSMODELAPIINT"; // 平台API接口
	public final static String PSSYSOUTYPERS = "PSSYSOUTYPERS"; // 系统组织单元类型关系
	public final static String PSAPPMENUITEM = "PSAPPMENUITEM"; // 应用菜单项
	public final static String PSDEVSLNSYSPATCH = "PSDEVSLNSYSPATCH"; // 系统打包版本补丁
	public final static String PSDEACTIONWIZARD = "PSDEACTIONWIZARD"; // 实体操作向导
	public final static String PSDEVIEWLOGIC = "PSDEVIEWLOGIC"; // 实体视图逻辑
	public final static String PSDEFORMRF = "PSDEFORMRF"; // 实体表单引用
	public final static String PSSYSVIEWPANEL = "PSSYSVIEWPANEL"; // 系统视图面板
	public final static String PSWFLINKCONDTYPE = "PSWFLINKCONDTYPE"; // 流程连接条件类型
	public final static String PSSYSDEPLOYAPP = "PSSYSDEPLOYAPP"; // 系统部署应用
	public final static String PSVTCATDETAIL = "PSVTCATDETAIL"; // 云视图类型分类成员
	public final static String PSAPPTYPE = "PSAPPTYPE"; // 云应用系统类型
	public final static String PSSYSBDCOLSET = "PSSYSBDCOLSET"; // 大数据表列族
	public final static String PSPFSTYLECODE = "PSPFSTYLECODE"; // 应用样式宏代码
	public final static String PSDEDSGRPPARAM = "PSDEDSGRPPARAM"; // 实体数据集分组参数
	public final static String PSDBSYSPROCTEMPL = "PSDBSYSPROCTEMPL"; // 数据库系统过程模版
	public final static String PSDETOOLBAR = "PSDETOOLBAR"; // 实体工具栏
	public final static String PSDEDUPRULEITEM = "PSDEDUPRULEITEM"; // 实体数据重复规则项
	public final static String PSDETREENODE = "PSDETREENODE"; // 实体树节点
	public final static String PSSYSTBITEM = "PSSYSTBITEM"; // 平台预置工具栏项
	public final static String PSDEWIZARDSTEP = "PSDEWIZARDSTEP"; // 实体向导步骤
	public final static String PSSYSPORTLET = "PSSYSPORTLET"; // 系统门户部件
	public final static String PSDEDRDETAIL = "PSDEDRDETAIL"; // 实体界面组成员
	public final static String PSWXMENUFUNC = "PSWXMENUFUNC"; // 微信菜单功能
	public final static String PSDEVCENTERPF = "PSDEVCENTERPF"; // 云应用中心应用框架
	public final static String PSDEDATAVIEW = "PSDEDATAVIEW"; // 实体数据视图
	public final static String PSDELNTYPE = "PSDELNTYPE"; // 云实体逻辑处理节点类型
	public final static String PSPFCODEFOLDER = "PSPFCODEFOLDER"; // 云应用代码目录
	public final static String PSSFCODEFOLDER = "PSSFCODEFOLDER"; // 系统服务代码目录
	public final static String PSSYSMODELACTION = "PSSYSMODELACTION"; // 云系统模块实例操作
	public final static String PSCOREPRDISSUE = "PSCOREPRDISSUE"; // 平台核心产品问题
	public final static String PSDEVIEWBASE = "PSDEVIEWBASE"; // 实体视图
	public final static String PSSYSPROJECT = "PSSYSPROJECT"; // 系统工程项目
	public final static String PSDBTYPE = "PSDBTYPE"; // 数据库类型
	public final static String PSDBSYSPROCTYPE = "PSDBSYSPROCTYPE"; // 数据库系统过程类型
	public final static String PSDEAWGRPDETAIL = "PSDEAWGRPDETAIL"; // 实体操作向导组成员
	public final static String PSDEMAP = "PSDEMAP"; // 实体映射
	public final static String PSDELLTYPE = "PSDELLTYPE"; // 云实体逻辑处理连接类型
	public final static String PSDEWIZARDFORM = "PSDEWIZARDFORM"; // 实体向导表单
	public final static String PSAPPSUBAPP = "PSAPPSUBAPP"; // 应用子应用
	public final static String PSDEDBIDXFIELD = "PSDEDBIDXFIELD"; // 实体数据库索引属性
	public final static String PSSYSDMITEMLOG = "PSSYSDMITEMLOG"; // 系统数据库模型关键变更
	public final static String PSTBITEMTYPE = "PSTBITEMTYPE"; // 平台工具栏项类型
	public final static String PSDCMODELTEMPL = "PSDCMODELTEMPL"; // 云应用中心模型模板
	public final static String PSDESPCODE = "PSDESPCODE"; // 系统存储过程代码
	public final static String PSBDDEVINST = "PSBDDEVINST"; // 平台大数据实例
	public final static String PSDBVALUEFUNC = "PSDBVALUEFUNC"; // 数据库值函数
	public final static String PSPFUATEMPL = "PSPFUATEMPL"; // 云应用界面行为代码模版
	public final static String PSCODENAME = "PSCODENAME"; // 代码名称库
	public final static String PSUAWIZARD2 = "PSUAWIZARD2"; // 界面操作向导2
	public final static String PSDCSERVERSTATE = "PSDCSERVERSTATE"; // 云应用中心主机状态
	public final static String PSSYSSFPUB = "PSSYSSFPUB"; // 系统后台服务体系
	public final static String PSSYSDBVF = "PSSYSDBVF"; // 系统数据库值函数
	public final static String PSDEVCENTERSVN = "PSDEVCENTERSVN"; // 云应用中心代码库
	public final static String PSHELPARTICLECAT = "PSHELPARTICLECAT"; // 帮助文章分类
	public final static String PSDELIST = "PSDELIST"; // 实体列表
	public final static String PSDEFVRCOND = "PSDEFVRCOND"; // 实体属性值规则项
	public final static String PSSYSCSS = "PSSYSCSS"; // 系统界面样式表
	public final static String PSDEVSLNSYSMODEL = "PSDEVSLNSYSMODEL"; // 开发系统模型
	public final static String PSDCINST = "PSDCINST"; // 云应用中心实例
	public final static String PSMODULE = "PSMODULE"; // 系统模块
	public final static String PSSYSERMAPNODE = "PSSYSERMAPNODE"; // 系统ER图节点
	public final static String PSSYSUCMAPNODE = "PSSYSUCMAPNODE"; // 系统UC图节点
	public final static String PSSYSREF = "PSSYSREF"; // 系统引用
	public final static String PSSYSVIEWLOGIC = "PSSYSVIEWLOGIC"; // 系统预置视图逻辑
	public final static String PSSYSVIEWLOGICPARAM = "PSSYSVIEWLOGICPARAM"; // 系统预置视图逻辑参数
	public final static String PSDCDBVIEW = "PSDCDBVIEW"; // 应用中心数据库视图
	public final static String PSDEVUSERGROUP = "PSDEVUSERGROUP"; // 云应用中心用户组
	public final static String PSDEFVALUERULE = "PSDEFVALUERULE"; // 实体属性值规则
	public final static String PSDELLCONDTYPE = "PSDELLCONDTYPE"; // 云实体逻辑处理连接条件类型
	public final static String PSSYSBDINSTCFG = "PSSYSBDINSTCFG"; // 系统大数据实例配置
	public final static String PSDEVUSERSQL = "PSDEVUSERSQL"; // 开发用户文件
	public final static String PSDETREEVIEW = "PSDETREEVIEW"; // 实体树视图
	public final static String PSCHARTTYPE = "PSCHARTTYPE"; // 平台图表类型
	public final static String PSAPPDEVIEW = "PSAPPDEVIEW"; // 应用实体视图
	public final static String PSDEAWGROUP = "PSDEAWGROUP"; // 实体操作向导组
	public final static String PSAPPINDEXVIEW = "PSAPPINDEXVIEW"; // 应用首页视图
	public final static String PSDEOPPRIV = "PSDEOPPRIV"; // 实体操作标识
	public final static String PSSYSDEOPPRIV = "PSSYSDEOPPRIV"; // 系统实体操作标识
	public final static String PSPF = "PSPF"; // 前台技术架构
	public final static String PSHELPPRJTYPE = "PSHELPPRJTYPE"; // 帮助项目类型
	public final static String PSHELPPRJTEMPL = "PSHELPPRJTEMPL"; // 帮助项目模板
	public final static String PSMODELPLUGIN = "PSMODELPLUGIN"; // 平台模型插件
	public final static String PSMODELMODULE = "PSMODELMODULE"; // 系统模型模块
	public final static String PSVARSAMPLEVALUE = "PSVARSAMPLEVALUE"; // 平台变量示例值
	public final static String PSCOREPRDINSTLOG = "PSCOREPRDINSTLOG"; // 核心产品安装日志
	public final static String PSMODELSECTION = "PSMODELSECTION"; // 系统模块章节
	public final static String PSMODELEXAMPLE = "PSMODELEXAMPLE"; // 系统模型例子
	public final static String PSMODELRESOURCE = "PSMODELRESOURCE"; // 系统模型资源
	public final static String PSRTWXACCOUNT = "PSRTWXACCOUNT"; // 平台运行微信企业号
	public final static String PSROBOTWORK = "PSROBOTWORK"; // 机器人作业
	public final static String PSDEMSOPPRIV = "PSDEMSOPPRIV"; // 实体主状态操作标识
	public final static String PSMODELOBJ = "PSMODELOBJ"; // 模型对象
	public final static String PSSYSVIEWPANELITEM = "PSSYSVIEWPANELITEM"; // 系统视图面板成员
	public final static String PSDEFGROUPDETAIL = "PSDEFGROUPDETAIL"; // 实体属性组成员
	public final static String PSDEFGROUP = "PSDEFGROUP"; // 实体属性组
	public final static String PSDEDOMAIN = "PSDEDOMAIN"; // 实体域对象
	public final static String PSDEDOMAINFIELD = "PSDEDOMAINFIELD"; // 实体域属性对象
	public final static String PSSYSSEARCHBAR = "PSSYSSEARCHBAR"; // 系统搜索栏
	public final static String PSSYSBDTABLEDER = "PSSYSBDTABLEDER"; // 大数据表关系
	public final static String PSSYSBDMODULE = "PSSYSBDMODULE"; // 大数据体系模块
	public final static String PSDEPSLNSYSAS = "PSDEPSLNSYSAS"; // 部署方案系统部署
	public final static String PSDEPSLNSYSMQ = "PSDEPSLNSYSMQ"; // 部署方案系统MQ
	public final static String PSDEPSLNSYSDB = "PSDEPSLNSYSDB"; // 部署方案系统数据库
	public final static String PSDEPSLNMQINST = "PSDEPSLNMQINST"; // 部署方案MQ实例
	public final static String PSDEPSLNSYS = "PSDEPSLNSYS"; // 部署方案系统
	public final static String PSSTUDIOSERVERGRP = "PSSTUDIOSERVERGRP"; // 平台开发工具服务器组
	public final static String PSDEPSAASSYSAPP = "PSDEPSAASSYSAPP"; // 部署SaaS系统应用（暂时废弃）
	public final static String PSDEPSAASSYSVER = "PSDEPSAASSYSVER"; // 部署SaaS系统版本（暂时废弃）
	public final static String PSDEPSAASSYS = "PSDEPSAASSYS"; // 部署SaaS系统（暂时废弃）
	public final static String PSDEPSYSAPP = "PSDEPSYSAPP"; // 部署系统应用
	public final static String PSDEPSYS = "PSDEPSYS"; // 可部署系统
	public final static String PSDEPSYSVER = "PSDEPSYSVER"; // 可部署系统版本
	public final static String PSDEPSLNHOST = "PSDEPSLNHOST"; // 部署方案主机
	public final static String PSSAASSYSDB = "PSSAASSYSDB"; // SaaS系统数据库
	public final static String PSDEPSLNPACK = "PSDEPSLNPACK"; // 部署方案打包
	public final static String PSDEPSLNDEPSESSION = "PSDEPSLNDEPSESSION"; // 部署方案部署操作
	public final static String PSGITUSER = "PSGITUSER"; // 平台GIT用户
	public final static String PSNDFILE = "PSNDFILE"; // 平台网盘文件
	public final static String PSNDFILELINK = "PSNDFILELINK"; // 平台网盘文件链接
	public final static String PSSYSENGINECFG = "PSSYSENGINECFG"; // 系统引擎配置
	public final static String PSDEVPRD = "PSDEVPRD"; // 开发产品
	public final static String PSDEVPRDVER = "PSDEVPRDVER"; // 开发产品主干
	public final static String PSDEVPRDSUBVER = "PSDEVPRDSUBVER"; // 开发产品版本
	public final static String PSDEVPRDSYS = "PSDEVPRDSYS"; // 开发产品系统
	public final static String PSDEVPRDSYSSYNC = "PSDEVPRDSYSSYNC"; // 开发产品系统同步
	public final static String PSDSBOOKINGLOG = "PSDSBOOKINGLOG"; // 平台开发主机预约日志
	public final static String PSDCDBINSTREF = "PSDCDBINSTREF"; // 应用中心数据库实例引用
	public final static String PSDEVPRDSYSSYNCITEM = "PSDEVPRDSYSSYNCITEM"; // 开发产品系统同步项
	public final static String PSDEVPRDSPEC = "PSDEVPRDSPEC"; // 开发产品规格
	public final static String PSDEVPRDSEPCPLAN = "PSDEVPRDSEPCPLAN"; // 开发产品规范计划（废弃）
	public final static String PSDEVPRDSPECPLAN = "PSDEVPRDSPECPLAN"; // 开发产品规范计划
	public final static String PSDEVSLNSYSRES = "PSDEVSLNSYSRES"; // 开发系统资源包
	public final static String PSPFCDN = "PSPFCDN"; // 应用框架CDN
	public final static String PSPFEDITORTYPE = "PSPFEDITORTYPE"; // 前端编辑器参数
	public final static String PSMODELERROR = "PSMODELERROR"; // 系统模型错误
	public final static String PSPFPKGVERCDN = "PSPFPKGVERCDN"; // 前端应用组件包版本CDN
	public final static String PSSYSMODELFUNCCAT = "PSSYSMODELFUNCCAT"; // 系统模型功能分类
	public final static String PSMODELSTATE = "PSMODELSTATE"; // 模型状态
	public final static String PSMODELVALUEGROUP = "PSMODELVALUEGROUP"; // 系统模型值组
	public final static String PSMODELFIELDVALUE = "PSMODELFIELDVALUE"; // 系统模型属性取值
	public final static String PSMODELFIELD = "PSMODELFIELD"; // 系统模型属性
	public final static String PSSFVIEWTYPE = "PSSFVIEWTYPE"; // 后台服务视图参数
	public final static String PSSFCTRLTYPE = "PSSFCTRLTYPE"; // 后台服务部件参数
	public final static String PSPFVIEWTYPE = "PSPFVIEWTYPE"; // 前端视图参数
	public final static String PSPFCTRLTYPE = "PSPFCTRLTYPE"; // 前端部件参数
	public final static String PSMODELUIACTION = "PSMODELUIACTION"; // 系统模型界面行为
	public final static String PSASBOOKING = "PSASBOOKING"; // 平台应用容器预约
	public final static String PSDEDTSQUEUE = "PSDEDTSQUEUE"; // 实体分布事务队列
	public final static String PSMODELEXAMPLESTEP = "PSMODELEXAMPLESTEP"; // 模型示例步骤
	public final static String PSMODELEXAMPLECAT = "PSMODELEXAMPLECAT"; // 模型实例分类
	public final static String PSMODELSUBVIEW = "PSMODELSUBVIEW"; // 模型子视图
	public final static String PSMODELVIEW = "PSMODELVIEW"; // 系统模型视图
	public final static String PSDEPSYSTYPE = "PSDEPSYSTYPE"; // 部署系统类型
	public final static String PSMQTYPE = "PSMQTYPE"; // 平台MQ类型
	public final static String PSDCASGROUP = "PSDCASGROUP"; // 应用中心应用容器组
	public final static String PSASGROUP = "PSASGROUP"; // 应用容器集群
	public final static String PSDEPSLNTYPE = "PSDEPSLNTYPE"; // 部署方案类型
	public final static String PSMODELVIEWUIACTION = "PSMODELVIEWUIACTION"; // 模型视图界面行为
	public final static String PSDCSYSLIC = "PSDCSYSLIC"; // 应用中心系统授权
	public final static String PSDCDBINSTBK = "PSDCDBINSTBK"; // 应用中心数据库备份
	public final static String PSDCSVNBK = "PSDCSVNBK"; // 应用中心SVN备份
	public final static String PSSAASSYSAPP = "PSSAASSYSAPP"; // SaaS系统应用
	public final static String PSSAASSYSVER = "PSSAASSYSVER"; // SaaS系统版本
	public final static String PSSAASSYS = "PSSAASSYS"; // SaaS系统
	public final static String PSDEVCENTERFILE = "PSDEVCENTERFILE"; // 应用中心文件
	public final static String PSSYSMODELMSG = "PSSYSMODELMSG"; // 系统模型消息
	public final static String PSDER_DERINHERIT = "PSDER_DERINHERIT"; // 实体关系（继承）
	public final static String PSDSBOOKING = "PSDSBOOKING"; // 平台开发主机预约
	public final static String PSDEPLOYSERVER = "PSDEPLOYSERVER"; // 平台部署服务器
	public final static String PSSTUDIOSERVERLOG = "PSSTUDIOSERVERLOG"; // 开发工具服务器日志
	public final static String PSDBDEVINSTBK = "PSDBDEVINSTBK"; // 数据库开发实例备份
	public final static String PSSYSMODELINSTBK = "PSSYSMODELINSTBK"; // 系统模型库备份
	public final static String PSSYSUNISTATE = "PSSYSUNISTATE"; // 系统状态协同
	public final static String PSSYSRTMSG = "PSSYSRTMSG"; // 系统模型运行信息
	public final static String PSSYSSQLCMD = "PSSYSSQLCMD"; // 系统数据库命令
	public final static String PSSYSSQLCMDSQL = "PSSYSSQLCMDSQL"; // 系统数据库命令代码
	public final static String PSDERTAW = "PSDERTAW"; // 实体运行操作向导库
	public final static String PSDERTAWI = "PSDERTAWI"; // 实体运行操作向导项
	public final static String PSSYSRTDEFINPUTTIP = "PSSYSRTDEFINPUTTIP"; // 系统运行属性输入提示
	public final static String PSMODELRTMSG = "PSMODELRTMSG"; // 模型运行消息
	public final static String PSROBOTTYPE = "PSROBOTTYPE"; // 平台机器人类型
	public final static String PSROBOTWORKTYPE = "PSROBOTWORKTYPE"; // 平台机器人能力类型
	public final static String PSROBOTTYPEABILITY = "PSROBOTTYPEABILITY"; // 机器人类型能力
	public final static String PSSUBSYSVERINST = "PSSUBSYSVERINST"; // 子系统版本实例
	public final static String PSCTRLMSGTAG = "PSCTRLMSGTAG"; // 平台部件消息标记
	public final static String PSBOOKINGRESTYPE = "PSBOOKINGRESTYPE"; // 平台预约资源类型
	public final static String PSDEFINPUTTIPSET = "PSDEFINPUTTIPSET"; // 系统属性输入提示集合
	public final static String PSDCNWFLOW = "PSDCNWFLOW"; // 应用中心流量
	public final static String PSDCROBOT = "PSDCROBOT"; // 应用中心机器人
	public final static String PSDCROBOTABILITY = "PSDCROBOTABILITY"; // 应用中心机器人能力
	public final static String PSDCROBOTLOG = "PSDCROBOTLOG"; // 中心机器人日志
	public final static String PSDCRTMSG = "PSDCRTMSG"; // 应用中心运行信息
	public final static String PSDCRESREP = "PSDCRESREP"; // 应用中心资源报告
	public final static String PSDCABILITY = "PSDCABILITY"; // 应用中心能力
	public final static String PSDCRESHOURSLOG = "PSDCRESHOURSLOG"; // 应用中心资源时间日志
	public final static String PSDCRESHOURS = "PSDCRESHOURS"; // 应用中心资源时间
	public final static String PSVIEWRTMSG = "PSVIEWRTMSG"; // 视图运行消息
	public final static String PSSYSMODELINSTSUM = "PSSYSMODELINSTSUM"; // 系统模型实例模型计数
	public final static String PSDCDEPLOYSERVER = "PSDCDEPLOYSERVER"; // 应用中心部署服务器
	public final static String PSSYSSEARCHBARITEM = "PSSYSSEARCHBARITEM"; // 系统搜索栏项
	public final static String PSROBOTABILITY = "PSROBOTABILITY"; // 机器人能力项
	public final static String PSDEUSERROLE = "PSDEUSERROLE"; // 实体操作能力
	public final static String PSDER_DERINDEX = "PSDER_DERINDEX"; // 实体关系（索引）
	public final static String PSDEFORMDETAIL_BUTTON = "PSDEFORMDETAIL_BUTTON"; // 表单成员（表单按钮）
	public final static String PSDEFORMDETAIL_FORMPART = "PSDEFORMDETAIL_FORMPART"; // 表单成员（表单部件）
	public final static String PSDEFORMDETAIL_FORMPAGE = "PSDEFORMDETAIL_FORMPAGE"; // 表单成员（表单分页）
	public final static String PSDEFORMDETAIL_FORMITEM = "PSDEFORMDETAIL_FORMITEM"; // 表单成员（表单项）
	public final static String PSDEFORMDETAIL_TABPANEL = "PSDEFORMDETAIL_TABPANEL"; // 表单成员（分页部件）
	public final static String PSDEFORMDETAIL_TABPAGE = "PSDEFORMDETAIL_TABPAGE"; // 表单成员（分页面板）
	public final static String PSDEFORMDETAIL_GROUPPANEL = "PSDEFORMDETAIL_GROUPPANEL"; // 表单成员（分组面板）
	public final static String PSDEFORMDETAIL_DATAGRID = "PSDEFORMDETAIL_DATAGRID"; // 表单成员（数据表格）
	public final static String PSDEFORMDETAIL_DRUIPART = "PSDEFORMDETAIL_DRUIPART"; // 表单成员（数据关系界面）
	public final static String PSDEFORMDETAIL_USERCONTROL = "PSDEFORMDETAIL_USERCONTROL"; // 表单成员（用户控件）
	public final static String PSDEFORMDETAIL_RAWITEM = "PSDEFORMDETAIL_RAWITEM"; // 表单成员（直接内容）
	public final static String PSDEFORMDETAIL_IFRAME = "PSDEFORMDETAIL_IFRAME"; // 表单成员（直接页面嵌入）
	public final static String PSDEFORMDETAIL_FORMITEMEX = "PSDEFORMDETAIL_FORMITEMEX"; // 表单成员（复合表单项）
	public final static String PSDEFORMDETAIL_MDCTRL = "PSDEFORMDETAIL_MDCTRL"; // 表单成员（多数据部件）
	public final static String PSDEFORMDETAIL_BUTTONLIST = "PSDEFORMDETAIL_BUTTONLIST"; // 表单成员（表单按钮列表）
	public final static String PSDEFORM_EDITFORM = "PSDEFORM_EDITFORM"; // 实体表单（编辑表单）
	public final static String PSDEFORM_SEARCHFORM = "PSDEFORM_SEARCHFORM"; // 实体表单（搜索表单）
	public final static String PSDCMOBAPPTESTDEVICE = "PSDCMOBAPPTESTDEVICE"; // 应用中心移动应用测试终端
	public final static String PSDCMOBAPPTDREF = "PSDCMOBAPPTDREF"; // 应用中心测试设备引用
	public final static String PSMOBAPPSTARTPAGE = "PSMOBAPPSTARTPAGE"; // 移动应用欢迎页
	public final static String PSMOBAPPPACKSESSION = "PSMOBAPPPACKSESSION"; // 移动应用打包会话
	public final static String PSDCMOBPACKCERT = "PSDCMOBPACKCERT"; // 应用中心移动端打包证书
	public final static String PSMODELRT = "PSMODELRT"; // 模型运行时
	public final static String PSMOBAPPPACKTD = "PSMOBAPPPACKTD"; // 移动应用打包测试设备
	public final static String PSSYSDEFTYPE = "PSSYSDEFTYPE"; // 系统属性类型默认逻辑
	public final static String PSSYSDELOGICNODE = "PSSYSDELOGICNODE"; // 系统逻辑处理节点
	public final static String PSDEVPRDISSUE = "PSDEVPRDISSUE"; // 开发产品问题
	public final static String PSDEVPRDISSUEPLAN = "PSDEVPRDISSUEPLAN"; // 开发产品问题修复计划
	public final static String PSDCPFPITEMPL = "PSDCPFPITEMPL"; // 应用中心前端插件模板
	public final static String PSDCPFPLUGIN = "PSDCPFPLUGIN"; // 应用中心前端应用插件
	public final static String PSMOBAPPPACKSERVER = "PSMOBAPPPACKSERVER"; // 移动应用打包服务器
	public final static String PSDCSYNCAGENT = "PSDCSYNCAGENT"; // 应用中心同步代理
	public final static String PSDCSYNCDATATYPE = "PSDCSYNCDATATYPE"; // 应用中心同步数据类型
	public final static String PSDCSYNCDATA = "PSDCSYNCDATA"; // 应用中心同步数据
	public final static String PSDCSYNCDATA2 = "PSDCSYNCDATA2"; // 应用中心同步输入数据
	public final static String PSSFPUBOBJPARAM = "PSSFPUBOBJPARAM"; // 服务模板发布对象参数
	public final static String PSSFPUBOBJ = "PSSFPUBOBJ"; // 服务模板发布对象
	public final static String PSPFPUBOBJ = "PSPFPUBOBJ"; // 应用模板发布对象
	public final static String PSPFPUBOBJPARAM = "PSPFPUBOBJPARAM"; // 应用模板发布对象参数
	public final static String PSDEOPPRIVROLE = "PSDEOPPRIVROLE"; // 实体操作标识角色
	public final static String PSDEVIEWCTRLDS = "PSDEVIEWCTRLDS"; // 视图部件附加数据集
	public final static String PSDELOGIC_VIEWLOGIC = "PSDELOGIC_VIEWLOGIC"; // 视图逻辑
	public final static String PSSYSDBPART = "PSSYSDBPART"; // 系统数据看板
	public final static String PSSYSMODELLOADLOG = "PSSYSMODELLOADLOG"; // 系统模型加载日志
	public final static String PSSYSDASHBOARD = "PSSYSDASHBOARD"; // 系统数据看板
	public final static String PSSYSUTILDE = "PSSYSUTILDE"; // 系统功能实体
	public final static String PSDEUTILDE = "PSDEUTILDE"; // 实体功能实体
	public final static String PSAPPLOCALDE = "PSAPPLOCALDE"; // 应用本地实体
	public final static String PSSYSUSERROLERES = "PSSYSUSERROLERES"; // 系统角色资源
	public final static String PSSYSSFPITEMPL = "PSSYSSFPITEMPL"; // 系统后台服务插件模板
	public final static String PSSYSSFPLUGIN = "PSSYSSFPLUGIN"; // 系统后台服务插件
	public final static String PSSFPLUGIN = "PSSFPLUGIN"; // 后台服务插件
	public final static String PSSFPLUGINTEMPL = "PSSFPLUGINTEMPL"; // 后台服务插件模板
	public final static String PSDEUTILTYPE = "PSDEUTILTYPE"; // 实体功能类型
	public final static String PSDEMODEL = "PSDEMODEL"; // 实体模型配置
	public final static String PSDEVIEWGRPDETAIL = "PSDEVIEWGRPDETAIL"; // 实体视图组成员
	public final static String PSDEVIEWGROUP = "PSDEVIEWGROUP"; // 系统实体视图组
	public final static String PSAPPUTIL = "PSAPPUTIL"; // 应用功能配置
	public final static String PSSYSCONSOLE = "PSSYSCONSOLE"; // 系统控制台信息
	public final static String PSDCCODESNIPPETREF = "PSDCCODESNIPPETREF"; // 应用中心代码模板引用
	public final static String PSDCCODESNIPPET = "PSDCCODESNIPPET"; // 中心代码片段
	public final static String PSSYSCODESNIPPET = "PSSYSCODESNIPPET"; // 系统代码块
	public final static String PSDEVSLNMSDEPAPI = "PSDEVSLNMSDEPAPI"; // 开发方案微服务服务部署
	public final static String PSDEVSLNSYSAPI = "PSDEVSLNSYSAPI"; // 开发系统服务接口
	public final static String PSDEVSLNSYSAPP = "PSDEVSLNSYSAPP"; // 开发系统应用
	public final static String PSDEVSLNMSDEPAPP = "PSDEVSLNMSDEPAPP"; // 开发方案微服务应用部署
	public final static String PSDEVSLNMSDEPLOY = "PSDEVSLNMSDEPLOY"; // 开发方案微服务部署
	public final static String PSDCMSPLATFORMNODE = "PSDCMSPLATFORMNODE"; // 中心微服务平台节点
	public final static String PSDCMSPLATFORMFUNC = "PSDCMSPLATFORMFUNC"; // 中心微服务平台功能
	public final static String PSDCMSPLATFORM = "PSDCMSPLATFORM"; // 中心微服务平台
	public final static String PSMSPLATFORMNODE = "PSMSPLATFORMNODE"; // 平台微服务平台节点
	public final static String PSMSPLATFORMFUNC = "PSMSPLATFORMFUNC"; // 平台微服务平台功能
	public final static String PSMSPLATFORM = "PSMSPLATFORM"; // 平台微服务平台
	public final static String PSDEPLOYCENTER = "PSDEPLOYCENTER"; // 平台部署中心
	public final static String PSCODESNIPPETTYPE = "PSCODESNIPPETTYPE"; // 平台代码片段类型
	public final static String PSDCDEPLOYCENTER = "PSDCDEPLOYCENTER"; // 应用中心部署中心
	public final static String PSWORKSHOPSERVER = "PSWORKSHOPSERVER"; // 平台系统工程服务器
	public final static String PSDCWORKSHOPSERVER = "PSDCWORKSHOPSERVER"; // 中心工程服务器
	public final static String PSAPPDEVIEWREF = "PSAPPDEVIEWREF"; // 应用实体视图引用
	public final static String PSDEDATAIMPITEM = "PSDEDATAIMPITEM"; // 实体数据导入项
	public final static String PSDEVSLNSYSWSGIT = "PSDEVSLNSYSWSGIT"; // 开发系统工程服务器GIT库
	public final static String PSSYSDYNAMODEL = "PSSYSDYNAMODEL"; // 系统动态模型对象
	public final static String PSSYSDYNAMODELATTR = "PSSYSDYNAMODELATTR"; // 系统动态模型属性
	public final static String PSSYSTITLEBAR = "PSSYSTITLEBAR"; // 系统标题栏
	public final static String PSAPPTITLEBAR = "PSAPPTITLEBAR"; // 应用标题栏
	public final static String PSDEACTIONPARAM = "PSDEACTIONPARAM"; // 实体行为参数
	public final static String PSDEACTIONINPUT = "PSDEACTIONINPUT"; // 实体行为输入对象
	public final static String PSDEACTIONRETURN = "PSDEACTIONRETURN"; // 实体行为返回对象
	public final static String PSDEDATASETINPUT = "PSDEDATASETINPUT"; // 实体数据集输入对象
	public final static String PSDEDATASETRETURN = "PSDEDATASETRETURN"; // 实体数据集返回对象
	public final static String PSDEDATAQUERYINPUT = "PSDEDATAQUERYINPUT"; // 实体数据查询输入对象
	public final static String PSDEDATAQUERYRETURN = "PSDEDATAQUERYRETURN"; // 实体数据查询返回对象
	
	public final static String PSDESERVICEAPIMETHODINPUT = "PSDESERVICEAPIMETHODINPUT"; // 实体服务接口方法输入对象
	public final static String PSDESERVICEAPIMETHODRETURN = "PSDESERVICEAPIMETHODRETURN"; // 实体服务接口方法返回对象
	public final static String PSDESERVICEAPIDTO = "PSDESERVICEAPIDTO"; // 实体服务接口DTO对象
	public final static String PSDESERVICEAPIDTOFIELD = "PSDESERVICEAPIDTOFIELD"; // 实体服务接口DTO属性对象
	
	public final static String PSSUBSYSSERVICEAPIMETHODINPUT = "PSSUBSYSSERVICEAPIMETHODINPUT"; // 外部服务接口方法输入对象
	public final static String PSSUBSYSSERVICEAPIMETHODRETURN = "PSSUBSYSSERVICEAPIMETHODRETURN"; // 外部服务接口方法返回对象
	public final static String PSSUBSYSSERVICEAPIDTO = "PSSUBSYSSERVICEAPIDTO"; // 外部服务接口DTO对象
	public final static String PSSUBSYSSERVICEAPIDTOFIELD = "PSSUBSYSSERVICEAPIDTOFIELD"; // 外部服务接口DTO属性对象
	
	
	/**
	 * 用户自定义开始
	 */
	public final static String PSSYSTEM_SETTING = "PSSYSTEM_SETTING"; // 系统设置
	public final static String PSSYSAPP_UI = "PSSYSAPP_UI"; // 应用界面设置
	public final static String PSSYSCOUNTERREF = "PSSYSCOUNTERREF"; // 系统计数器引用
	public final static String PSDEGRIDEDITITEM = "PSDEGRIDEDITITEM"; // 实体表格编辑项
	public final static String PSDEGRIDDATAITEM = "PSDEGRIDDATAITEM"; // 实体表格数据项
	public final static String PSACHANDLER_GRIDEDITITEM = "PSACHANDLER_GRIDEDITITEM"; // 表格编辑项后台处理器
	public final static String PSACHANDLER_FORMITEM = "PSACHANDLER_FORMITEM"; // 表单项后台处理器
	public final static String PSACHANDLER_PANELFIELD = "PSACHANDLER_PANELFIELD"; // 面板后台处理器
	public final static String PSCUSTOMCONTROL = "PSCUSTOMCONTROL"; // 自定义部件
	public final static String PSDELLCOND_GROUP = "PSDELLCOND_GROUP"; // 实体处理逻辑组合连接
	public final static String PSDELLCOND_SINGLE = "PSDELLCOND_SINGLE"; // 实体处理逻辑单项条件
	public final static String PSDELLCOND_CUSTOM = "PSDELLCOND_CUSTOM"; // 实体处理逻辑自定义条件
	public final static String PSDEDRBAR = "PSDEDRBAR"; // 实体数据关系栏
	public final static String PSDEDRTAB = "PSDEDRTAB"; // 实体数据关系分页部件
	public final static String PSDEDRBARGROUP = "PSDEDRBARGROUP"; // 实体数据关系栏分组
	public final static String PSDEDRBARITEM = "PSDEDRBARITEM"; // 实体数据关系栏项目
	public final static String PSWFUIACTION = "PSWFUIACTION"; // 工作流界面行为
	public final static String PSDEDATAEXPITEM = "PSDEDATAEXPITEM"; // 实体数据导出项
	public final static String PSDEDATAEXPGROUP = "PSDEDATAEXPGROUP"; // 实体数据导出分组
	public final static String PSDECHARTTITLE = "PSDECHARTTITLE"; // 实体图表标题
	public final static String PSDECHARTCOORDINATESYSTEM = "PSDECHARTCOORDINATESYSTEM"; // 实体图表坐标系统
	public final static String PSDECHARTLEGEND = "PSDECHARTLEGEND"; // 实体图表图例
	public final static String PSDECHARTDATAGRID = "PSDECHARTDATAGRID"; // 实体图表数据图表
	public final static String PSDECHARTGRID = "PSDECHARTGRID"; // 实体图表直角坐标表格
	public final static String PSDECHARTGRIDXAXIS = "PSDECHARTGRIDXAXIS"; // 实体图表直角坐标表格X轴
	public final static String PSDECHARTGRIDYAXIS = "PSDECHARTGRIDYAXIS"; // 实体图表直角坐标表格Y轴
	public final static String PSDECHARTGEO = "PSDECHARTGEO"; // 实体地理坐标系组件
	public final static String PSDECHARTCALENDAR = "PSDECHARTCALENDAR"; // 实体日历坐标系组件
	public final static String PSDECHARTDATASET = "PSDECHARTDATASET"; // 实体图表数据集
	public final static String PSDECHARTDATASETFIELD = "PSDECHARTDATASETFIELD"; // 实体图表数据集属性
	public final static String PSDECHARTDATASETGROUP = "PSDECHARTDATASETGROUP"; // 实体图表数据集分组

	public final static String PSDECHARTPOLARANGLEAXIS = "PSDECHARTPOLARANGLEAXIS"; // 实体图表极坐标角度轴
	public final static String PSDECHARTPOLARRADIUSAXIS = "PSDECHARTPOLARRADIUSAXIS"; // 实体图表极坐标径向轴
	public final static String PSDECHARTPARALLELAXIS = "PSDECHARTPARALLELAXIS"; // 实体图表平行坐标轴
	public final static String PSDECHARTSINGLEAXIS = "PSDECHARTSINGLEAXIS"; // 实体图表单一坐标轴
	public final static String PSDECHARTSERIESENCODE = "PSDECHARTSERIESENCODE"; // 实体图表序列编码

	public final static String PSDECHARTRADAR = "PSDECHARTRADAR"; // 实体图表雷达部件
	public final static String PSDECHARTPOLAR = "PSDECHARTPOLAR"; // 实体图表极坐标系组件
	public final static String PSDECHARTPARALLEL = "PSDECHARTPARALLEL"; // 实体图表平行坐标系组件
	public final static String PSDECHARTSINGLE = "PSDECHARTSINGLE"; // 实体图表单一坐标系组件
	public final static String PSDEUNISTATE = "PSDEUNISTATE"; // 实体统一状态
	public final static String PSDEDATAVIEWDATAITEM = "PSDEDATAVIEWDATAITEM"; // 实体数据视图数据项
	public final static String PSEXPBAR = "PSEXPBAR"; // 导航栏
	public final static String PSWFUAGROUP = "PSWFUAGROUP"; // 工作流界面行为组
	public final static String PSWFUAGRPDETAIL = "PSWFUAGRPDETAIL"; // 工作流界面行为组成员
	public final static String PSDELISTDATAITEM = "PSDELISTDATAITEM"; // 实体列表数据项
	public final static String PSVIEWPANEL = "PSVIEWPANEL"; // 视图面板
	public final static String PSDEWIZARDPANEL = "PSDEWIZARDPANEL"; // 向导面板
	public final static String PSDECONTEXTMENU = "PSDECONTEXTMENU"; // 实体上下文菜单
	public final static String PSSYSDTSQUEUE = "PSSYSDTSQUEUE"; // 系统分布事务队列
	public final static String PSDEREPORTPANEL = "PSDEREPORTPANEL"; // 实体报表面板
	public final static String PSSYSDMVER = "PSSYSDMVER"; // 系统数据库模型版本
	public final static String PSDEACTIONTEMPL = "PSDEACTIONTEMPL"; // 系统实体行为模板
	public final static String PSDETREECOL = "PSDETREECOL"; // 树视图表格列
	public final static String PSDETREENODECOL = "PSDETREENODECOL"; // 树节点数据项
	public final static String PSSYSCALENDAR = "PSSYSCALENDAR"; // 系统日历部件
	public final static String PSSYSCALENDARITEM = "PSSYSCALENDARITEM"; // 系统日历部件项
	public final static String PSSYSCALENDARITEMRV = "PSSYSCALENDARITEMRV"; // 系统日历部件项视图
	public final static String PSDESAMPLEDATA = "PSDESAMPLEDATA"; // 实体示例数据

	public final static String PSSYSVIEWPANELITEM_CONTAINER = "PSSYSVIEWPANELITEM_CONTAINER"; // 系统面板容器部件
	public final static String PSSYSVIEWPANELITEM_FIELD = "PSSYSVIEWPANELITEM_FIELD"; // 系统面板字段部件
	public final static String PSSYSVIEWPANELITEM_TABPANEL = "PSSYSVIEWPANELITEM_TABPANEL"; // 系统面板分页部件
	public final static String PSSYSVIEWPANELITEM_TABPAGE = "PSSYSVIEWPANELITEM_TABPAGE"; // 系统面板分页面板
	public final static String PSSYSVIEWPANELITEM_CONTROL = "PSSYSVIEWPANELITEM_CONTROL"; // 系统面板部件
	public final static String PSSYSVIEWPANELITEM_CTRLPOS = "PSSYSVIEWPANELITEM_CTRLPOS"; // 系统面板部件占位
	public final static String PSSYSVIEWPANELITEM_USERCONTROL = "PSSYSVIEWPANELITEM_USERCONTROL"; // 系统面板自定义部件
	public final static String PSSYSVIEWPANELITEM_RAWITEM = "PSSYSVIEWPANELITEM_RAWITEM"; // 系统面板直接内容
	public final static String PSSYSVIEWPANELITEM_BUTTON = "PSSYSVIEWPANELITEM_BUTTON"; // 系统面板按钮
	public final static String PSSYSVIEWPANELITEM_BUTTONLIST = "PSSYSVIEWPANELITEM_BUTTONLIST"; // 系统面板按钮列表
	public final static String PSSYSVIEWPANELITEM_PARAM = "PSSYSVIEWPANELITEM_PARAM"; // 系统面板项参数

	public final static String PSSYSVIEWPANELMODEL = "PSSYSVIEWPANELMODEL"; // 系统面板模型
	public final static String PSSYSVIEWPANELLOGIC = "PSSYSVIEWPANELLOGIC"; // 系统面板逻辑
	public final static String PSPANELLOGICPARAM = "PSPANELLOGICPARAM"; // 面板逻辑参数
	public final static String PSPANELLOGICNODE = "PSPANELLOGICNODE"; // 面板逻辑节点
	public final static String PSPANELLOGICLINK = "PSPANELLOGICLINK"; // 面板逻辑连接

	public final static String PSPANELLLCOND = "PSPANELLLCOND"; // 面板逻辑连接条件
	public final static String PSPANELLNPARAM = "PSPANELLNPARAM"; // 面板逻辑节点参数

	public final static String PSPANELLLCOND_GROUP = "PSPANELLLCOND_GROUP"; // 实体处理逻辑组合连接
	public final static String PSPANELLLCOND_SINGLE = "PSPANELLLCOND_SINGLE"; // 实体处理逻辑单项条件
	public final static String PSPANELLLCOND_CUSTOM = "PSPANELLLCOND_CUSTOM"; // 实体处理逻辑自定义条件

	public final static String PSAPPDYNADEVIEW = "PSAPPDYNADEVIEW"; // 应用动态实体视图
	public final static String PSAPPUTILVIEW = "PSAPPUTILVIEW"; // 应用功能视图
	public final static String PSDEVSLNMSDEPFUNC = "PSDEVSLNMSDEPFUNC"; // 开发方案微服务功能部署
	public final static String PSAPPPANELVIEW = "PSAPPPANELVIEW"; // 应用面板视图
	public final static String PSSYSVIEWLAYOUTPANEL = "PSSYSVIEWLAYOUTPANEL"; // 系统布局面板

	public final static String PSAPPVIEWLOGICREFVIEW = "PSAPPVIEWLOGICREFVIEW"; // 视图逻辑引用视图
	public final static String PSAPPVIEWENGINE = "PSAPPVIEWENGINE"; // 视图界面引擎
	public final static String PSAPPVIEWENGINEPARAM = "PSAPPVIEWENGINEPARAM"; // 视图界面引擎参数
	public final static String PSAPPDATAENTITY = "PSAPPDATAENTITY"; // 应用实体
	public final static String PSAPPVIEWPARAM = "PSAPPVIEWEPARAM"; // 应用视图参数
	public final static String PSAPPVIEWNAVCONTEXT = "PSAPPVIEWNAVCONTEXT"; // 应用视图导航上下文
	public final static String PSAPPVIEWNAVPARAM = "PSAPPVIEWNAVPARAM"; // 应用视图导航参数
	public final static String PSCONTROLNAVCONTEXT = "PSCONTROLNAVCONTEXT"; // 部件导航上下文
	public final static String PSCONTROLNAVPARAM = "PSCONTROLNAVPARAM"; // 部件导航参数
	public final static String PSLAYOUT = "PSLAYOUT"; // 布局容器
	public final static String PSLAYOUTPOS = "PSLAYOUTPOS"; // 布局位置
	public final static String PSAPPVIEWUIACTION = "PSAPPVIEWUIACTION"; // 应用视图界面行为

	public final static String PSCONTROLLOGIC = "PSCONTROLLOGIC"; // 部件逻辑
	public final static String PSAPPLICATIONLOGIC = "PSAPPLICATIONLOGIC"; // 应用逻辑

	public final static String PSAPPUILOGIC = "PSAPPUILOGIC"; // 系统预置视图逻辑
	public final static String PSAPPUILOGICBUILDIN = "PSAPPUILOGICBUILDIN"; // 系统预置视图逻辑

	public final static String PSDEMAPACTION = "PSDEMAPACTION"; // 实体映射行为
	public final static String PSDEMAPDQ = "PSDEMAPDQ"; // 实体映射查询
	public final static String PSDEMAPDS = "PSDEMAPDS"; // 实体映射数据集合

	public final static String PSTABEXPPANEL = "PSTABEXPPANEL"; // 分页导航面板
	public final static String PSDEDRTABPAGE = "PSDEDRTABPAGE"; // 实体数据关系分页部件成员
	public final static String PSPFXCODEOBJECT = "PSPFXCODEOBJECT"; // 前端扩展对象
	public final static String PSSFXCODEOBJECT = "PSSFXCODEOBJECT"; // 后端扩展对象
	public final static String PSAPPWF = "PSAPPWF"; // 应用工作流
	public final static String PSAPPWFVER = "PSAPPWFVER"; // 应用工作流版本
	public final static String PSAPPWFDE = "PSAPPWFDE"; // 应用工作流实体
	public final static String PSDESERVICEAPIFIELD = "PSDESERVICEAPIFIELD"; // 实体服务接口属性
	public final static String PSDESARS = "PSDESARS"; // 实体服务接口关系
	public final static String PSAPPDERS = "PSAPPDERS"; // 应用实体关系
	public final static String PSAPPDERSVIEW = "PSAPPDERSVIEW"; // 应用实体关系视图

	public final static String PSSUBSYSSADE = "PSSUBSYSSADE"; // 子系统接口实体
	public final static String PSSUBSYSSADERS = "PSSUBSYSSADERS"; // 子系统接口实体关系
	public final static String PSSUBSYSSADEFIELD = "PSSUBSYSSADEFIELD"; // 子系统接口实体属性

	public final static String PSSYSDBSCHEME = "PSSYSDBSCHEME"; // 系统数据库架构
	public final static String PSSYSDBTABLE = "PSSYSDBTABLE"; // 数据库表对象
	public final static String PSSYSDBCOLUMN = "PSSYSDBCOLUMN"; // 数据库列对象
	public final static String PSDESAVR = "PSDESAVR"; // 实体接口值规则
	public final static String PSSYSRESOURCE = "PSSYSRESOURCE"; // 系统预置资源
	public final static String PSSYSCONTENT = "PSSYSCONTENT"; // 系统预置内容
	public final static String PSAPPRESOURCE = "PSAPPRESOURCE"; // 应用预置资源

	public final static String PSAPPDEMETHOD = "PSAPPDEMETHOD"; // 应用实体方法
	public final static String PSAPPDEFIELD = "PSAPPDEFIELD"; // 应用实体属性
	public final static String PSAPPDEMETHODLOGIC = "PSAPPDEMETHODLOGIC"; // 应用实体方法附加逻辑

	public final static String PSAPPDEUIACTION = "PSAPPDEUIACTION"; // 应用实体界面行为
	public final static String PSSYSAPPDEUIACTION = "PSSYSAPPDEUIACTION"; // 全局应用实体界面行为

	public final static String PSDEGROUPDETAIL = "PSDEGROUPDETAIL"; // 实体组成员
	public final static String PSDEGROUP = "PSDEGROUP"; // 实体组
	public final static String PSSYSDEGROUPDETAIL = "PSSYSDEGROUPDETAIL"; // 系统实体组成员
	public final static String PSSYSDEGROUP = "PSSYSDEGROUP"; // 系统实体组
	public final static String PSDERGROUPDETAIL = "PSDERGROUPDETAIL"; // 实体关系组成员
	public final static String PSSYSDERGROUPDETAIL = "PSSYSDERGROUPDETAIL"; // 系统实体关系组成员
	public final static String PSDERGROUP = "PSDERGROUP"; // 实体关系组
	public final static String PSSYSDERGROUP = "PSSYSDERGROUP"; // 全局实体关系组
	public final static String PSDEACTIONGROUP = "PSDEACTIONGROUP"; // 实体行为组
	public final static String PSDEAGDETAIL = "PSDEAGDETAIL"; // 实体行为组成员
	public final static String PSSYSCONTENTCAT = "PSSYSCONTENTCAT"; // 系统内容分类
	public final static String PSDERNN = "PSDERNN"; // 实体多对多关系
	public final static String PSSYSSAHANDLER = "PSSYSSAHANDLER"; // 系统服务接口处理
	public final static String PSDETABLE = "PSDETABLE"; // 实体数据库表
	public final static String PSAPPCOUNTER = "PSAPPCOUNTER"; // 应用计数器
	public final static String PSAPPCODELIST = "PSAPPCODELIST"; // 应用代码表
	public final static String PSAPPMSGTEMPL = "PSAPPMSGTEMPL"; // 应用消息模板
	public final static String PSAPPWFUTILUIACTION = "PSAPPWFUTILUIACTION"; // 应用工作流功能界面行为

	public final static String PSAPPVIEWMSG = "PSAPPVIEWMSG"; // 应用视图消息
	public final static String PSAPPVIEWMSGGROUP = "PSAPPVIEWMSGGROUP"; // 应用视图消息组
	public final static String PSAPPVIEWMSGGRPDETAIL = "PSAPPVIEWMSGGRPDETAIL"; // 应用视图消息组成员

	public final static String PSAPPDELOGIC = "PSAPPDELOGIC"; // 应用实体处理逻辑
	public final static String PSAPPDELOGICNODE = "PSAPPDELOGICNODE"; // 应用实体处理逻辑节点
	public final static String PSAPPDELOGICPARAM = "PSAPPDELOGICPARAM"; // 应用实体逻辑参数
	public final static String PSAPPDELOGICLINK = "PSAPPDELOGICLINK"; // 应用实体逻辑连接
	public final static String PSAPPDELLCOND = "PSAPPDELLCOND"; // 应用实体逻辑连接条件
	public final static String PSAPPDELNPARAM = "PSAPPDELNPARAM"; // 应用实体逻辑节点参数
	public final static String PSCTRLLOGICGROUP = "PSCTRLLOGICGROUP"; // 界面逻辑组
	public final static String PSCTRLLOGICGRPDETAIL = "PSCTRLLOGICGRPDETAIL"; // 界面逻辑组成员
	public final static String PSSYSCTRLLOGICGROUP = "PSSYSCTRLLOGICGROUP"; // 全局界面逻辑组
	public final static String PSSYSCTRLLOGICGRPDETAIL = "PSSYSCTRLLOGICGRPDETAIL"; // 全局界面逻辑组成员

	public final static String PSPANELITEMLOGIC = "PSPANELITEMLOGIC"; // 面板成员逻辑项
	public final static String PSPANELENGINE = "PSPANELENGINE"; // 面板界面引擎
	public final static String PSPANELENGINEPARAM = "PSPANELENGINEPARAM"; // 面板界面引擎参数

	public final static String PSDEUILOGIC = "PSDEUILOGIC"; // 实体界面逻辑
	public final static String PSDEUILOGICPARAM = "PSDEUILOGICPARAM"; // 实体界面逻辑参数
	public final static String PSDEUILOGICNODE = "PSDEUILOGICNODE"; // 实体界面逻辑节点
	public final static String PSDEUILOGICLINK = "PSDEUILOGICLINK"; // 实体界面逻辑连接
	public final static String PSDEUILNPARAM = "PSDEUILNPARAM"; // 实体界面逻辑节点参数
	public final static String PSDEUILLCOND = "PSDEUILLCOND"; // 实体界面逻辑连接条件
	public final static String PSAPPDEUILOGIC = "PSAPPDEUILOGIC"; // 应用实体界面逻辑
	public final static String PSAPPDEUILOGICNODE = "PSAPPDEUILOGICNODE"; // 应用实体界面处理逻辑节点
	public final static String PSAPPDEUILOGICPARAM = "PSAPPDEUILOGICPARAM"; // 应用实体界面逻辑参数
	public final static String PSAPPDEUILOGICLINK = "PSAPPDEUILOGICLINK"; // 应用实体界面逻辑连接
	public final static String PSAPPDEUILLCOND = "PSAPPDEUILLCOND"; // 应用实体界面逻辑连接条件
	public final static String PSAPPDEUILNPARAM = "PSAPPDEUILNPARAM"; // 应用实体界面逻辑节点参数
	public final static String PSAPPDEACMODE = "PSAPPDEACMODE"; // 应用实体自填模式
	public final static String PSAPPDEACMODEITEM = "PSAPPDEACMODEITEM"; // 应用实体自填模式项
	public final static String PSEDITOR = "PSEDITOR"; // 编辑器对象
	public final static String PSEDITORITEM = "PSEDITORITEM"; // 复合编辑器项对象
	public final static String PSSYSMODELGROUP = "PSSYSMODELGROUP"; // 系统模型组

	public final static String PSSYSSEARCHSCHEME = "PSSYSSEARCHSCHEME"; // 全文检索体系
	public final static String PSSYSSEARCHDOC = "PSSYSSEARCHDOC"; // 全文检索文档
	public final static String PSSYSSEARCHDE = "PSSYSSEARCHDE"; // 全文检索实体
	public final static String PSSYSSEARCHFIELD = "PSSYSSEARCHFIELD"; // 全文检索属性
	public final static String PSSYSSEARCHDEFIELD = "PSSYSSEARCHDEFIELD"; // 全文检索实体属性
	public final static String PSDESEARCH = "PSDESEARCH"; // 实体全文检索
	public final static String PSDEFSEARCH = "PSDEFSEARCH"; // 实体属性全文检索
	public final static String PSDEBDTABLE = "PSDEBDTABLE"; // 实体大数据表

	public final static String PSSYSMAPVIEW = "PSSYSMAPVIEW"; // 系统地图部件
	public final static String PSSYSMAPITEM = "PSSYSMAPITEM"; // 系统地图项

	// public final static String PSSYSGANTT = "PSSYSGANTT"; //系统甘特部件
	// public final static String PSSYSGANTTITEM = "PSSYSGANTTITEM"; //系统甘特部件项
	// public final static String PSSYSGANTTITEMRV = "PSSYSGANTTITEMRV";
//系统甘特部件项视图

	public final static String PSAPPWFUIACTION = "PSAPPWFUIACTION"; // 应用流程界面行为
	public final static String PSAPPWFVERUIACTION = "PSAPPWFVERUIACTION"; // 应用流程版本界面行为
	public final static String PSAPPWFUAGROUP = "PSAPPWFUAGROUP"; // 应用流程界面行为组
	public final static String PSAPPWFVERUAGROUP = "PSAPPWFVERUAGROUP"; // 应用流程版本界面行为组
	public final static String PSAPPWFUAGRPDETAIL = "PSAPPWFUAGRPDETAIL"; // 应用流程界面行为组成员
	public final static String PSAPPWFVERUAGRPDETAIL = "PSAPPWFVERUAGRPDETAIL"; // 应用流程版本界面行为组成员

	public final static String PSSYSPORTLETCAT = "PSSYSPORTLETCAT"; // 系统门户部件分类
	public final static String PSAPPPORTLET = "PSAPPPORTLET"; // 应用门户部件
	public final static String PSAPPPORTLETCAT = "PSAPPPORTLETCAT"; // 应用门户部件分类

	public final static String PSAPPDEDRITEM = "PSAPPDEDRITEM"; // 应用实体关系界面项
	public final static String PSAPPDEDRGROUP = "PSAPPDEDRGROUP"; // 应用实体关系界面分组
	public final static String PSAPPDEPORTLET = "PSAPPDEPORTLET"; // 应用实体门户部件
	public final static String PSSYSUSERROLEDATA = "PSSYSUSERROLEDATA"; // 系统角色数据能力
	public final static String PSSYSUSERROLE = "PSSYSUSERROLE"; // 系统角色
	public final static String PSAPPPDTVIEW = "PSAPPPDTVIEW"; // 应用预置视图

	public final static String PSAPPDEPRINT = "PSAPPDEPRINT"; // 应用实体打印
	public final static String PSAPPDEDATAEXP = "PSAPPDEDATAEXP"; // 应用实体数据导出
	public final static String PSAPPDEDATAEXPITEM = "PSAPPDEDATAEXPITEM"; // 应用实体数据导出项
	public final static String PSAPPDEDATAEXPGROUP = "PSAPPDEDATAEXPGROUP"; // 应用实体数据导出分组
	
	public final static String PSAPPDEDATAIMP = "PSAPPDEDATAIMP"; // 应用实体数据导入
	public final static String PSAPPDEDATAIMPITEM = "PSAPPDEDATAIMPITEM"; // 应用实体数据导入项
	public final static String PSAPPVALUERULE = "PSAPPVALUERULE"; // 应用值规则
	public final static String PSDATAITEMPARAM = "PSDATAITEMPARAM"; // 数据项参数
	public final static String PSDEFORMDATAITEM = "PSDEFORMDATAITEM"; // 实体表单数据项
	public final static String PSDEDATAVIEWITEM = "PSDEDATAVIEWITEM"; // 实体卡片视图项
	public final static String PSSYSPANELDATAITEM = "PSSYSPANELDATAITEM"; // 系统面板数据项
	public final static String PSDEACMODEDATAITEM = "PSDEACMODEDATAITEM"; // 实体自填数据项
	public final static String PSAPPDEACMODEDATAITEM = "PSAPPDEACMODEDATAITEM"; // 应用实体自填数据项
	public final static String PSCONTROL = "PSCONTROL"; // 界面部件
	public final static String PSDCWORKSPACE = "PSDCWORKSPACE"; // 中心生产线

	public final static String PSDETREENODERSPARAM = "PSDETREENODERSEPARAM"; // 树节点关系参数
	public final static String PSDETREENODERSNAVCONTEXT = "PSDETREENODERSNAVCONTEXT"; // 树节点关系导航上下文
	public final static String PSDETREENODERSNAVPARAM = "PSDETREENODERSNAVPARAM"; // 树节点关系导航参数

	public final static String PSSFPUBHELP = "PSSFPUBHELP"; // 后台模板发布帮助
	public final static String PSPFPUBHELP = "PSPFPUBHELP"; // 前端模板发布帮助

	public final static String PSSFCODEPUBLISHERMACRO = "PSSFCODEPUBLISHERMACRO"; // 后台模板发布器宏变量
	public final static String PSPFCODEPUBLISHERMACRO = "PSPFCODEPUBLISHERMACRO"; // 前端模板发布器宏变量
	public final static String PSSFCODEPUBLISHERPARAM = "PSSFCODEPUBLISHERPARAM"; // 后台模板发布器内置变量
	public final static String PSPFCODEPUBLISHERPARAM = "PSPFCODEPUBLISHERPARAM"; // 前端模板发布器内置变量

	public final static String PSDETREEGRIDEX = "PSDETREEGRIDEX"; // 树表格部件
	public final static String PSDEGANTT = "PSDEGANTT"; // 甘特部件
	public final static String PSDESARSDETAIL = "PSDESARSDETAIL"; // 实体服务接口关系成员
	public final static String PSDEGEIVR = "PSDEGEIVR"; // 实体表格编辑项值规则
	public final static String PSDEKANBAN = "PSDEKANBAN"; // 看板部件

	public final static String PSSYSSEARCHBARFILTER = "PSSYSSEARCHBARFILTER"; // 搜索栏过滤项
	public final static String PSSYSSEARCHBARQUICKSEARCH = "PSSYSSEARCHBARQUICKSEARCH"; // 搜索栏快速搜索项
	public final static String PSSYSSEARCHBARGROUP = "PSSYSSEARCHBARGROUP"; // 搜索栏分组项

	public final static String PSNAVIGATECONTEXT = "PSNAVIGATECONTEXT"; // 导航视图导航上下文
	public final static String PSNAVIGATEPARAM = "PSNAVIGATEPARAM"; // 导航视图导航参数

	public final static String PSUIACTIONPARAM = "PSUIACTIONPARAM"; // 界面行为参数
	public final static String PSDER1NDEFMAP = "PSDER1NDEFMAP"; // 实体1:N关系属性映射
	public final static String PSDERINDEXDEFMAP = "PSDERINDEXDEFMAP"; // 实体索引关系属性映射
	public final static String PSDERAGGDATADEFMAP = "PSDERAGGDATADEFMAP"; // 实体聚合数据关系属性映射

	public final static String PSDEMETHOD = "PSDEMETHOD"; // 实体方法
	public final static String PSDEACTIONMETHOD = "PSDEACTIONMETHOD"; // 实体行为方法
	public final static String PSDEDATASETMETHOD = "PSDEDATASETMETHOD"; // 实体数据集方法
	public final static String PSDEACTIONVR = "PSDEACTIONVR"; // 实体行为值规则
	public final static String PSDESTATEWIZARDPANEL = "PSDESTATEWIZARDPANEL"; // 状态向导面板

	public final static String PSDEFLOGIC = "PSDEFLOGIC"; // 实体属性逻辑
	public final static String PSAPPDEFLOGIC = "PSAPPDEFLOGIC"; // 实体属性逻辑

	public final static String PSDEFUIMODE = "PSDEFUIMODE"; // 实体属性界面模式
	public final static String PSDEFGRIDCOLUMN = "PSDEFGRIDCOLUMN"; // 属性表格列模式
	public final static String PSAPPDEFUIMODE = "PSAPPDEFUIMODE"; // 实体属性界面模式
	public final static String PSAPPDEFGRIDCOLUMN = "PSAPPDEFGRIDCOLUMN"; // 属性表格列模式
	
	public final static String PSDEMSFIELD = "PSDEMSFIELD"; // 实体主状态属性
	public final static String PSSYSDBVALUEOP = "PSSYSDBVALUEOP"; // 系统值操作
	
	public final static String PSAPPPFPLUGINREF = "PSAPPPFPLUGINREF";	 //应用前端模板插件引用
	public final static String PSAPPEDITORSTYLEREF = "PSAPPEDITORSTYLEREF";	 //应用编辑器样式引用
	public final static String PSAPPSUBVIEWTYPEREF = "PSAPPSUBVIEWTYPEREF";	 //应用子视图类型引用
	
	
	public final static String PSSYSSEQUENCE = "PSSYSSEQUENCE"; // 系统值序列
	public final static String PSSYSTRANSLATOR = "PSSYSTRANSLATOR"; // 系统值转换器
	
	
	public final static String PSSYSMSGQUEUE = "PSSYSMSGQUEUE"; // 系统消息队列
	public final static String PSSYSMSGTARGET = "PSSYSMSGTARGET"; // 系统消息目标
	public final static String PSDENOTIFY = "PSDENOTIFY"; // 实体通知
	public final static String PSDENOTIFYTARGET = "PSDENOTIFYTARGET"; // 实体通知目标
	
	//20210505 添加
	public final static String PSSYSEAIDATATYPEITEM = "PSSYSEAIDATATYPEITEM"; // 集成数据类型项
	public final static String PSSYSEAIDER = "PSSYSEAIDER"; // 集成实体关系映射
	public final static String PSSYSEAIDEFIELD = "PSSYSEAIDEFIELD"; // 集成实体属性映射
	public final static String PSSYSEAIDE = "PSSYSEAIDE"; // 集成实体映射
	public final static String PSSYSEAIELEMENTRE = "PSSYSEAIELEMENTRE"; // 集成元素元素
	public final static String PSSYSEAIELEMENTATTR = "PSSYSEAIELEMENTATTR"; // 集成元素属性
	public final static String PSSYSEAIELEMENT = "PSSYSEAIELEMENT"; // 集成元素
	public final static String PSSYSEAIDATATYPE = "PSSYSEAIDATATYPE"; // 集成数据类型
	public final static String PSSYSEAISCHEME = "PSSYSEAISCHEME"; // 应用集成体系
	public final static String PSSYSBIAGGCOLUMN = "PSSYSBIAGGCOLUMN"; // 智能报表聚合数据列
	public final static String PSSYSBIAGGTABLE = "PSSYSBIAGGTABLE"; // 智能报表聚合数据
	public final static String PSSYSBICUBELEVEL = "PSSYSBICUBELEVEL"; // 智能报表立方体维度层级
	public final static String PSSYSBICUBEMEASURE = "PSSYSBICUBEMEASURE"; // 智能报表立方体指标
	public final static String PSSYSBICUBEDIMENSION = "PSSYSBICUBEDIMENSION"; // 智能报表立方体维度
	public final static String PSSYSBILEVEL = "PSSYSBILEVEL"; // 智能报表维度层级
	public final static String PSSYSBIHIERARCHY = "PSSYSBIHIERARCHY"; // 智能报表维度体系
	public final static String PSSYSBIDIMENSION = "PSSYSBIDIMENSION"; // 智能报表维度
	public final static String PSSYSBICUBE = "PSSYSBICUBE"; // 智能报表立方体
	public final static String PSSYSBISCHEME = "PSSYSBISCHEME"; // 智能报表体系
	public final static String PSTHRESHOLD = "PSTHRESHOLD"; // 阈值项
	public final static String PSTHRESHOLDGROUP = "PSTHRESHOLDGROUP"; // 阈值组
	public final static String PSSYSCHARTTHEME = "PSSYSCHARTTHEME"; // 系统图表主题
	public final static String PSSYSCANVAS = "PSSYSCANVAS"; // 系统画布
	public final static String PSSYSCANVASMODEL = "PSSYSCANVASMODEL"; // 系统画布引用模型
	
	public final static String PSDEMSLOGIC = "PSDEMSLOGIC"; // 实体主状态迁移逻辑
	public final static String PSDEMSLOGICPARAM = "PSDEMSLOGICPARAM"; // 实体主状态迁移逻辑参数
	public final static String PSDEMSLOGICNODE = "PSDEMSLOGICNODE"; // 实体主状态迁移逻辑节点
	public final static String PSDEMSLOGICLINK = "PSDEMSLOGICLINK"; // 实体主状态迁移逻辑连接
	public final static String PSDEMSLNPARAM = "PSDEMSLNPARAM"; // 实体主状态迁移逻辑节点参数
	public final static String PSDEMSLLCOND = "PSDEMSLLCOND"; // 实体主状态迁移逻辑连接条件
	
	
	public final static String PSSUBSYSSERVICEAPIDE = "PSSUBSYSSERVICEAPIDE"; // 外部服务接口实体
	
	public final static String PSDEMETHODDTO = "PSDEMETHODDTO"; // 实体方法DTO对象
	public final static String PSDEMETHODDTOFIELD = "PSDEMETHODDTOFIELD"; // 实体方法DTO属性对象
	
	public final static String PSAPPDEMETHODDTO = "PSAPPDEMETHODDTO"; // 应用实体方法DTO对象
	public final static String PSAPPDEMETHODDTOFIELD = "PSAPPDEMETHODDTOFIELD"; // 应用实体方法DTO属性对象
	
	public final static String PSAPPDEMETHODINPUT = "PSAPPDEMETHODINPUT"; // 应用实体方法输入对象
	public final static String PSAPPDEMETHODRETURN = "PSAPPDEMETHODRETURN"; // 应用实体方法返回对象
	
	
	public final static String PSJSONSCHEMA = "PSJSONSCHEMA"; // JSONSchema
	public final static String PSJSONNODESCHEMA = "PSJSONNODESCHEMA"; // JsonNodeShema
	public final static String PSJSONPROPERTY = "PSJSONPROPERTY"; //JsonProperty
	public final static String PSJSONPROPERTIES = "PSJSONPROPERTIES"; //JsonProperties
	
	public final static String PSJSONDEF = "PSJSONDEF"; //Json节点定义
	public final static String PSJSONDEFS = "PSJSONDEFS"; //Json节点定义集合
	
	
	
	public final static String PSOPENAPI3SCHEMA = "PSOPENAPI3SCHEMA"; // OpenAPI Schema
	public final static String PSOPENAPI3INFO = "PSOPENAPI3INFO"; // OpenAPI Info
	
	public final static String PSOPENAPI3CONTACT = "PSOPENAPI3CONTACT"; // OpenAPI Contact
	public final static String PSOPENAPI3LICENSE = "PSOPENAPI3LICENSE"; // OpenAPI License

	public final static String PSOPENAPI3JSONSCHEMA = "PSOPENAPI3JSONSCHEMA"; // OpenAPI JsonSchema
	public final static String PSOPENAPI3JSONNODESCHEMAS = "PSOPENAPI3JSONNODESCHEMAS"; // OpenAPI JsonNodeSchemas
	
	public final static String PSOPENAPI3PARAMETER = "PSOPENAPI3PARAMETER"; // OpenAPI Parameter
	public final static String PSOPENAPI3PARAMETERS = "PSOPENAPI3PARAMETERS"; // OpenAPI Parameters
	
	public final static String PSOPENAPI3PATH = "PSOPENAPI3PATH"; // OpenAPI Path
	public final static String PSOPENAPI3PATHS = "PSOPENAPI3PATHS"; // OpenAPI Paths
	
	public final static String PSOPENAPI3OPERATION = "PSOPENAPI3OPERATION"; // OpenAPI Operation
	
	public final static String PSOPENAPI3COMPONENTS = "PSOPENAPI3COMPONENTS"; // OpenAPI Components
	
	public final static String PSOPENAPI3MEDIATYPE = "PSOPENAPI3MEDIATYPE"; // OpenAPI MediaType
	public final static String PSOPENAPI3MEDIATYPES = "PSOPENAPI3MEDIATYPES"; // OpenAPI MediaTypes
	
	public final static String PSOPENAPI3RESPONSE = "PSOPENAPI3RESPONSE"; // OpenAPI Response
	public final static String PSOPENAPI3RESPONSES = "PSOPENAPI3RESPONSES"; // OpenAPI Responses
	
	public final static String PSOPENAPI3REQUESTBODY = "PSOPENAPI3REQUESTBODY"; // OpenAPI RequestBody
	public final static String PSOPENAPI3REQUESTBODIES = "PSOPENAPI3REQUESTBODIES"; // OpenAPI RequestBodies
	
	public final static String PSLIQUIBASECHANGELOG = "PSLIQUIBASECHANGELOG"; // Liquibase ChangeLog
	public final static String PSLIQUIBASECHANGESETS = "PSLIQUIBASECHANGESETS"; // Liquibase ChangeSets
	public final static String PSLIQUIBASECHANGESET = "PSLIQUIBASECHANGESET"; // Liquibase ChangeSet
	public final static String PSLIQUIBASEACTIONS = "PSLIQUIBASEACTIONS"; // Liquibase Actions
	public final static String PSLIQUIBASEACTION = "PSLIQUIBASEACTION"; // Liquibase Action
	public final static String PSLIQUIBASECOLUMNS = "PSLIQUIBASECOLUMNS"; // Liquibase Columns
	public final static String PSLIQUIBASECOLUMN = "PSLIQUIBASECOLUMN"; // Liquibase Columns
	public final static String PSLIQUIBASECREATETABLE = "PSLIQUIBASECREATETABLE"; // Liquibase CreateTable
	public final static String PSLIQUIBASECONSTRAINTS = "PSLIQUIBASECONSTRAINTS"; // Liquibase Constraints
	
	public final static String PSSYSUSECASE = "PSSYSUSECASE"; // 系统用例
	public final static String PSSYSUSECASERS = "PSSYSUSECASERS"; // 系统用例关系
	
	public final static String PSSYSDBINDEX = "PSSYSDBINDEX"; // 系统数据库索引
	public final static String PSSYSDBINDEXCOLUMN = "PSSYSDBINDEXCOLUMN"; //系统数据库索引列
	public final static String PSSYSI18N = "PSSYSI18N"; // 系统国际化
	
	
	public final static String PSSYSMETHODDTO = "PSSYSMETHODDTO"; // 系统方法DTO对象
	public final static String PSSYSMETHODDTOFIELD = "PSSYSMETHODDTOFIELD"; // 系统方法DTO属性对象
	
	public final static String PSAPPMETHODDTO = "PSAPPMETHODDTO"; // 应用方法DTO对象
	public final static String PSAPPMETHODDTOFIELD = "PSAPPMETHODDTOFIELD"; // 应用方法DTO属性对象
	
	public final static String PSAPPDEREPORT = "PSAPPDEREPORT"; // 应用实体报表
	public final static String PSAPPDEREPITEM = "PSAPPDEREPITEM"; // 应用实体报表项
	
	public final static String PSSYSDASHBOARDLOGIC = "PSSYSDASHBOARDLOGIC"; //数据看板逻辑
	public final static String PSAPPMENULOGIC = "PSAPPMENULOGIC"; //应用菜单逻辑
	public final static String PSDEFORMLOGIC = "PSDEFORMLOGIC"; //实体表单逻辑
	public final static String PSSYSSEARCHBARLOGIC = "PSSYSSEARCHBARLOGIC"; //搜索栏逻辑
	public final static String PSAPPLOGIC = "PSAPPLOGIC"; //前端应用逻辑
	public final static String PSDETOOLBARLOGIC = "PSDETOOLBARLOGIC"; //工具栏逻辑
	public final static String PSDEWIZARDLOGIC = "PSDEWIZARDLOGIC"; //实体向导逻辑
	public final static String PSDELISTLOGIC = "PSDELISTLOGIC"; //实体列表逻辑
	public final static String PSSYSMAPLOGIC = "PSSYSMAPLOGIC"; //地图部件逻辑
	public final static String PSDETREELOGIC = "PSDETREELOGIC"; //实体树视图逻辑
	public final static String PSDEDATAVIEWLOGIC = "PSDEDATAVIEWLOGIC"; //卡片视图部件逻辑
	public final static String PSSYSCALENDARLOGIC = "PSSYSCALENDARLOGIC"; //日历部件逻辑
	public final static String PSDEGRIDLOGIC = "PSDEGRIDLOGIC"; //实体表格逻辑
	public final static String PSDECHARTLOGIC = "PSDECHARTLOGIC"; //实体图表逻辑
	
	public final static String PSCAPTIONBAR = "PSCAPTIONBAR"; //标题栏
	public final static String PSDEDRLOGIC = "PSDEDRLOGIC"; //实体关系界面组逻辑
	
	public final static String PSCONTROLRENDER = "PSCONTROLRENDER"; // 部件绘制器
	public final static String PSCONTROLATTRIBUTE = "PSCONTROLATTRIBUTE"; // 部件注入属性
	
	public final static String PSDATAINFOBAR = "PSDATAINFOBAR"; //数据信息栏
	
	
	  /**
     * 实体[系统面板逻辑]
     */
    public static final String PSSYSPANELLOGIC = "PSSYSPANELLOGIC";
	
    
    public final static String PSDEDATAFLOW = "PSDEDATAFLOW"; // 实体数据流
	public final static String PSDEDATAFLOWNODE = "PSDEDATAFLOWNODE"; // 实体数据流节点
	public final static String PSDEDATAFLOWLINK = "PSDEDATAFLOWLINK"; // 实体数据流连接
	public final static String PSDEDFNODEPARAM = "PSDEDFNODEPARAM"; // 实体数据流节点参数
	public final static String PSDEDFFILTERCOND = "PSDEDFFILTERCOND"; // 实体数据流过滤器条件
	public final static String PSDEDFJOINCOND = "PSDEDFJOINCOND"; // 实体数据流连接条件
	public final static String PSDEDFNODEFILTER = "PSDEDFNODEFILTER"; // 实体数据流节点过滤器
	public final static String PSDETREENODEEDITITEM = "PSDETREENODEEDITITEM"; // 实体树节点编辑项
	public final static String PSDETREENODEDATAITEM = "PSDETREENODEDATAITEM"; // 实体树节点数据项
	
	
	public final static String PSDETEIUPDATE = "PSDETEIUPDATE"; // 树表编辑项更新模式
	public final static String PSDETEIUDETAIL = "PSDETEIUDETAIL"; // 树表编辑项更新成员
	
	
	public final static String PSAPPBISCHEME = "PSAPPBISCHEME"; //应用智能报表体系
	public final static String PSAPPBICUBE = "PSAPPBICUBE"; //应用智能立方体
	public final static String PSAPPBICUBEDIMENSION = "PSAPPBICUBEDIMENSION"; //应用智能立方体维度
	public final static String PSAPPBICUBEHIERARCHY = "PSAPPBICUBEHIERARCHY"; //应用智能立方体维度体系
	public final static String PSAPPBICUBELEVEL = "PSAPPBICUBELEVEL"; //应用智能立方体维度体系层级
	public final static String PSAPPBICUBEMEASURE = "PSAPPBICUBEMEASURE"; //应用智能立方体维度
	
	public final static String PSAPPBIREPORT = "PSAPPBIREPORT"; //应用智能报表
	public final static String PSAPPBIREPORTDIMENSION = "PSAPPBIREPORTDIMENSION"; //应用智能报表维度
	public final static String PSAPPBIREPORTMEASURE = "PSAPPBIREPORTMEASURE"; //应用智能报表维度
	
	public final static String PSSYSBIREPORT = "PSSYSBIREPORT"; // 系统智能报表
	public final static String PSSYSBIREPORTITEM = "PSSYSBIREPORTITEM"; // 系统智能报表项
	public final static String PSSYSBIREPORTITEM_DIMENSION = "PSSYSBIREPORTITEM_DIMENSION"; // 系统智能报表维度
	public final static String PSSYSBIREPORTITEM_MEASURE = "PSSYSBIREPORTITEM_MEASURE"; // 系统智能报表指标
	
	
	public final static String PSAPPPFPLUGIN = "PSAPPPFPLUGIN"; // 应用前端插件
	public final static String PSSYSAICHATAGENT = "PSSYSAICHATAGENT";//系统AI交谈代理
	public final static String PSSYSAIFACTORY = "PSSYSAIFACTORY";//系统AI工厂
	public final static String PSSYSAIPIPELINEAGENT = "PSSYSAIPIPELINEAGENT";//系统AI生产线代理
	public final static String PSSYSAIPIPELINEJOB = "PSSYSAIPIPELINEJOB";//系统AI生产线作业
	public final static String PSSYSAIPIPELINEWORKER = "PSSYSAIPIPELINEWORKER";//AI生产线工作者
	public final static String PSSYSAIWORKERAGENT = "PSSYSAIWORKERAGENT";//系统AI工作者代理
	
	public final static String PSAPPDEMAP = "PSAPPDEMAP"; // 应用实体映射
	public final static String PSAPPDEMAPFIELD = "PSAPPDEMAPFIELD"; // 应用实体映射属性
	public final static String PSAPPDEMAPACTION = "PSAPPDEMAPACTION"; // 应用实体映射行为
	public final static String PSAPPDEMAPDS = "PSAPPDEMAPDS"; // 应用实体映射数据集
	
	public final static String PSAPPDEFINPUTTIPSET = "PSAPPDEFINPUTTIPSET"; // 应用实体属性输入提示集
    
    
}