package net.ibizsys.central.cloud.saas.ebsx.uaa.logic.userlogic.deletesysuser;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import net.ibizsys.central.cloud.saas.ebsx.util.errors.BadRequestAlertException;
                global net.ibizsys.central.cloud.saas.ebsx.core.uaa.domain.User userdeletesysuserdefault;
                    global net.ibizsys.central.cloud.saas.ebsx.core.uaa.service.IUserService userservice;
        global net.ibizsys.central.cloud.saas.ebsx.core.uaa.service.IUserService iBzSysUserDefaultService;
        global net.ibizsys.central.cloud.saas.ebsx.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "userdeletesysuserbegin"
            when
            then
            end

            //逻辑处理节点[同步删除用户]
            rule "deaction1"
            ruleflow-group "userdeletesysuserdeaction1"
            when
            then
                        userservice.remove(userdeletesysuserdefault.getUserid());
                        update(userdeletesysuserdefault);//更新fact中变量值
            end