package net.ibizsys.central.cloud.saas.ebsx.uaa.logic.userlogic.savesysuser;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import net.ibizsys.central.cloud.saas.ebsx.util.errors.BadRequestAlertException;
                global net.ibizsys.central.cloud.saas.ebsx.core.uaa.domain.User usersavesysuserdefault;
                    global net.ibizsys.central.cloud.saas.ebsx.core.uaa.service.IUserService userservice;
        global net.ibizsys.central.cloud.saas.ebsx.core.uaa.service.IUserService iBzSysUserDefaultService;
        global net.ibizsys.central.cloud.saas.ebsx.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "usersavesysuserbegin"
            when
            then
            end

            //逻辑处理节点[设置用户为管理员]
            rule "prepareparam1"
            ruleflow-group "usersavesysuserprepareparam1"
            when
            then
                            usersavesysuserdefault.set("superuser","1");
                        update(usersavesysuserdefault);//更新fact中变量值
            end

            //逻辑处理节点[保存用户]
            rule "deaction2"
            ruleflow-group "usersavesysuserdeaction2"
            when
            then
                        userservice.save(usersavesysuserdefault);
                        update(usersavesysuserdefault);//更新fact中变量值
            end

            //逻辑处理节点[保存用户]
            rule "deaction1"
            ruleflow-group "usersavesysuserdeaction1"
            when
            then
                        userservice.save(usersavesysuserdefault);
                        update(usersavesysuserdefault);//更新fact中变量值
            end