package net.ibizsys.central.cloud.saas.v2.notify.logic.internal_messagelogic.mark_all_read;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import net.ibizsys.central.cloud.saas.v2.util.errors.BadRequestAlertException;
                global net.ibizsys.central.cloud.saas.v2.core.notify.domain.internal_message internal_messagemark_all_readdefault;
        global net.ibizsys.central.cloud.saas.v2.core.notify.service.Iinternal_messageService iBzSysInternal_messageDefaultService;
        global net.ibizsys.central.cloud.saas.v2.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "internal_messagemark_all_readbegin"
            when
            then
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "internal_messagemark_all_readrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
        param.put("param1",curuser.getSessionParams().get("srfdcsystemid"));
    String strSql="UPDATE `INTERNAL_MESSAGE` t1 SET t1.`STATUS` = 'READ'  WHERE  ( ( t1.`STATUS` = 'RECEIVED' )  AND  t1.`RECEIVER` = #{et.param0}   AND  t1.`SYSTEM_TAG` = #{et.param1} )";
                        iBzSysInternal_messageDefaultService.execute(strSql,param);//SQL调用
                        update(internal_messagemark_all_readdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "internal_messagemark_all_readend1"
            when
            then
                        update(internal_messagemark_all_readdefault);//更新fact中变量值
            end