package net.ibizsys.central.cloud.saas.v2.notify.logic.internal_messagelogic.mark_read;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import net.ibizsys.central.cloud.saas.v2.util.errors.BadRequestAlertException;
                global net.ibizsys.central.cloud.saas.v2.core.notify.domain.internal_message internal_messagemark_readdefault;
                    global net.ibizsys.central.cloud.saas.v2.core.notify.service.Iinternal_messageService internal_messageservice;
        global net.ibizsys.central.cloud.saas.v2.core.notify.service.Iinternal_messageService iBzSysInternal_messageDefaultService;
        global net.ibizsys.central.cloud.saas.v2.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "internal_messagemark_readbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "internal_messagemark_readend1"
            when
            then
                        update(internal_messagemark_readdefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "internal_messagemark_readprepareparam1"
            when
            then
                            internal_messagemark_readdefault.set("status","READ");
                        update(internal_messagemark_readdefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "internal_messagemark_readdeaction1"
            when
            then
                        internal_messageservice.update(internal_messagemark_readdefault);
                        update(internal_messagemark_readdefault);//更新fact中变量值
            end