package net.ibizsys.model.app.view;



/**
 * 应用功能视图模型对象接口
 * <P>
 * 扩展父接口类型[APPUTILVIEW,APPSTARTVIEW,APPWELCOMEVIEW,APPLOGINVIEW,APPLOGOUTVIEW,APPFILEUPLOADVIEW,APPPICUPLOADVIEW,APPDATAUPLOADVIEW,APPFUNCPICKUPVIEW,APPERRORVIEW,APPWFSTEPDATAVIEW,APPWFSTEPACTORVIEW,APPWFSTEPTRACEVIEW,APPWFSENDBACKVIEW,APPWFSUPPLYINFOVIEW,APPWFADDSTEPBEFOREVIEW,APPWFTAKEADVICEVIEW,APPWFREDIRECTVIEW,APPREDIRECTVIEW]
 *
 */
public interface IPSAppUtilView extends net.ibizsys.model.app.view.IPSAppView{

}