package net.ibizsys.model.app.view;



/**
 * 应用功能视图模型对象接口，标准模型{@link net.ibizsys.centralstudio.dto.PSAppUtilViewDTO}运行时对象
 * <P>
 * 子接口扩展识别值 {@link #getViewType}
 * <P>
 * 扩展父接口类型[APPUTILVIEW,APPSTARTVIEW,APPWELCOMEVIEW,APPLOGINVIEW,APPLOGOUTVIEW,APPFILEUPLOADVIEW,APPPICUPLOADVIEW,APPDATAUPLOADVIEW,APPFUNCPICKUPVIEW,APPERRORVIEW,APPWFSTEPDATAVIEW,APPWFSTEPACTORVIEW,APPWFSTEPTRACEVIEW,APPWFSENDBACKVIEW,APPWFSUPPLYINFOVIEW,APPWFADDSTEPBEFOREVIEW,APPWFTAKEADVICEVIEW,APPWFREDIRECTVIEW,APPREDIRECTVIEW]
 *
 */
public interface IPSAppUtilView extends net.ibizsys.model.app.view.IPSAppView{

}