<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>cn.ibizlab.plugin</groupId>
		<artifactId>ibiz-plugin</artifactId>
		<version>8.1.0.584.1</version>
    </parent>
	<artifactId>ibiz-cloud-kb-core</artifactId>
	<name>ibiz-cloud-kb-core</name>
	<properties>
		<maven-jar-plugin.version>2.6</maven-jar-plugin.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>cn.ibizlab.plugin</groupId>
			<artifactId>ibiz-cloud-core</artifactId>
			<version>${ibiz.cloud.version}</version>
		</dependency>

		<!-- Source: https://mvnrepository.com/artifact/org.apache.jackrabbit/jackrabbit-core -->
		<dependency>
			<groupId>org.apache.jackrabbit</groupId>
			<artifactId>jackrabbit-core</artifactId>
			<version>2.20.17</version>
			<scope>compile</scope>
		</dependency>

		<!-- Source: https://mvnrepository.com/artifact/org.apache.jackrabbit/jackrabbit-webdav -->
		<dependency>
			<groupId>org.apache.jackrabbit</groupId>
			<artifactId>jackrabbit-webdav</artifactId>
			<version>2.20.17</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>javax.jcr</groupId>
			<artifactId>jcr</artifactId>
			<version>2.0</version>
		</dependency>

		<!-- Source: https://mvnrepository.com/artifact/org.apache.jackrabbit/jackrabbit-jcr-commons -->
		<dependency>
			<groupId>org.apache.jackrabbit</groupId>
			<artifactId>jackrabbit-jcr-commons</artifactId>
			<version>2.20.17</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.jackrabbit</groupId>
			<artifactId>jackrabbit-jcr-server</artifactId>
			<version>2.20.17</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>