package net.ibizsys.central.cloud.saas.ebsx.ou.logic.deptmemberlogic.savedeptmember;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import net.ibizsys.central.cloud.saas.ebsx.util.errors.BadRequestAlertException;
                global net.ibizsys.central.cloud.saas.ebsx.core.ou.domain.DeptMember deptmembersavedeptmemberdefault;
                    global net.ibizsys.central.cloud.saas.ebsx.core.ou.service.IDeptMemberService deptmemberservice;
        global net.ibizsys.central.cloud.saas.ebsx.core.ou.service.IDeptMemberService iBzSysDeptmemberDefaultService;
        global net.ibizsys.central.cloud.saas.ebsx.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "deptmembersavedeptmemberbegin"
            when
            then
            end

            //逻辑处理节点[准备sysuser参数]
            rule "prepareparam1"
            ruleflow-group "deptmembersavedeptmemberprepareparam1"
            when
            then
                            deptmembersavedeptmemberdefault.set("deptid",deptmembersavedeptmemberdefault.get("mdeptid"));
                            deptmembersavedeptmemberdefault.set("deptname",deptmembersavedeptmemberdefault.get("mdeptname"));
                        update(deptmembersavedeptmemberdefault);//更新fact中变量值
            end

            //逻辑处理节点[保存部门用户]
            rule "deaction1"
            ruleflow-group "deptmembersavedeptmemberdeaction1"
            when
            then
                        deptmemberservice.save(deptmembersavedeptmemberdefault);
                        update(deptmembersavedeptmemberdefault);//更新fact中变量值
            end